### ISSUE TITLE
作者 专辑无法合并

### ISSUE THREAD

**Issue by CaseyMao** [karimknaebel/phonograph-issue-tracker#100]
新下载的歌曲，如题
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1 BETA 1</td></tr>
<tr><td>App version code</td><td>116</td></tr>
<tr><td>Android build version</td><td>373</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>ONE A2001_24_160630</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus2</td></tr>
<tr><td>Device model</td><td>ONE A2001</td></tr>
<tr><td>Device product name</td><td>OnePlus2</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by arkon** [comment]
Translation: artist - album can't merge for new tracks
