### ISSUE TITLE
Issue changing any info/art (Possibly related to SD card?)

### ISSUE THREAD

**Issue by AndyOHart** [karimknaebel/phonograph-issue-tracker#102]
Hey.
On my Galaxy S7 Edge, Android 6.0.1 with a MicroSD card of 128gb, I can't change any artist information. 
If I update an album cover, I see it change and I press save, but when I go back I don't see it updated, and same happens if I change song names or whatever.

It's the only thing stopping me from using the app all the time.
Not sure if it is related to the SD card, as Poweramp seems to let me modify this stuff and the change is seen on Phonograph.

**Comment by arkon** [comment]
Duplicate of #26
