### ISSUE TITLE
Wasted space on Artist and Album 'Page title' bar

### ISSUE THREAD

**Issue by Susko3** [karimknaebel/phonograph-issue-tracker#106]
If you scroll down on artist or album page so the image dissapears, you can see wasted space as a unnecessary double 'Page title' bar. Album and artist name could be put after the back arrow.

![screenshot_20160712-170730](https://cloud.githubusercontent.com/assets/16479013/16772588/1949c660-4855-11e6-8b57-069bd6bebeda.png)
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>31</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MPB24.65-34</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>titan_umtsds</td></tr>
<tr><td>Device model</td><td>XT1068</td></tr>
<tr><td>Device product name</td><td>titan_retde</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by simonmclean** [comment]
I agree that implementation is not great from a UI point of view. As @Susko3 said, the artist/album title could shrink and/or be re-positioned when you scroll down. At the moment there is a lot of wasted space.

**Comment by aexvir** [comment]
Agree with this issue, this needs some rework, right now the wasted space is too big

**Comment by arkon** [comment]
Being tracked in https://github.com/kabouzeid/Phonograph/issues/163.
