### ISSUE TITLE
Option for circular thumbnails in grid size 1 view

### ISSUE THREAD

**Issue by simonmclean** [karimknaebel/phonograph-issue-tracker#110]
It would be nice to have the option with grid size 1 to use circular thumbnails. This would be in-keeping with material design implementations from many other apps. See the example below.
![app](https://cloud.githubusercontent.com/assets/14262306/16814330/40dd5d4e-492d-11e6-8e61-4b8471d885c4.png)

**Comment by arkon** [comment]
I don't think this really fits with Phonograph's design.
