### ISSUE TITLE
Genre tab

### ISSUE THREAD

**Issue by anik9x** [karimknaebel/phonograph-issue-tracker#111]
The app itself is perfect, without doubt. If you could add the genre tab though, it would be even better. Thank you for creating and giving us such a wonderful app.
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>2964546</td></tr>
<tr><td>Android release version</td><td>N</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NPD56N</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>bullhead</td></tr>
<tr><td>Device model</td><td>Nexus 5X</td></tr>
<tr><td>Device product name</td><td>bullhead</td></tr>
<tr><td>Device hardware name</td><td>bullhead</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by ghost** [comment]
+1, the app is otherwise fabulous but I listen to my music mainly by genre which depends on current mood. Im a dev and I already made this, its not that hard to implement...

**Comment by trinadyerra264** [comment]
This is an awesome app. Please add genre tab in the app. Please also add an option to sort the album's year wise. Thanks a lot for this wonderful app.

**Comment by arkon** [comment]
Tracking this here: https://github.com/kabouzeid/Phonograph/issues/235
