### ISSUE TITLE
Wrong album art displayed

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#113]
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>G935VVRU2APE1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.G935VVRU2APE1</td></tr>
<tr><td>Device brand</td><td>Verizon</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>hero2qltevzw</td></tr>
<tr><td>Device model</td><td>SM-G935V</td></tr>
<tr><td>Device product name</td><td>hero2qltevzw</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by arkon** [comment]
This should be "fixed" if you use the "Ignore Media Store covers" setting.
