### ISSUE TITLE
EQ menu popup msg

### ISSUE THREAD

**Issue by King0nion** [karimknaebel/phonograph-issue-tracker#117]
Every single buttonpress in EQ menu while EQ is off equals one popup message saying "press the power button on the top right". Mesaage appears even after leaving EQ menu.
I suggest either displaying the msg once every time you enter EQ menu, or not at all.
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>V7.5.1.0.LHJCNDE</td></tr>
<tr><td>Android release version</td><td>5.1.1</td></tr>
<tr><td>Android SDK version</td><td>22</td></tr>
<tr><td>Android build ID</td><td>LMY47V</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>HM2014813</td></tr>
<tr><td>Device model</td><td>2014813</td></tr>
<tr><td>Device product name</td><td>2014813</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
This is your ROM's equalizer, not Phonograph's.
