### ISSUE TITLE
Gaallery photos replacing album art

### ISSUE THREAD

**Issue by darthbatman12** [karimknaebel/phonograph-issue-tracker#119]
the album art in thumbnails is random gallery photos, but in the album's panel it shows up correctly.
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>C605B150</td></tr>
<tr><td>Android release version</td><td>5.0.1</td></tr>
<tr><td>Android SDK version</td><td>21</td></tr>
<tr><td>Android build ID</td><td>ALE-L23C605B150</td></tr>
<tr><td>Device brand</td><td>Huawei</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>hwALE-H</td></tr>
<tr><td>Device model</td><td>ALE-L23</td></tr>
<tr><td>Device product name</td><td>ALE-L23</td></tr>
<tr><td>Device hardware name</td><td>hi6210sft</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by aexvir** [comment]
Also happening on my CM13 Snapshot with 0.13.2 Beta 1

**Comment by arkon** [comment]
Duplicate of #84
