### ISSUE TITLE
Same name - 2 different artists 

### ISSUE THREAD

**Issue by asherheilbron** [karimknaebel/phonograph-issue-tracker#12]
I have two artists with the same name, and they appear under 1 name. Is there something I can do to solve this? 
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.0 BETA 2</td></tr>
<tr><td>App version code</td><td>112</td></tr>
<tr><td>Android build version</td><td>e36dd78050</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29V</td></tr>
<tr><td>Device brand</td><td>oneplus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>A0001</td></tr>
<tr><td>Device model</td><td>A0001</td></tr>
<tr><td>Device product name</td><td>bacon</td></tr>
<tr><td>Device hardware name</td><td>bacon</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by karimknaebel** [comment]
No
