### ISSUE TITLE
Lyrics on double tap or swipe

### ISSUE THREAD

**Issue by lomarence** [karimknaebel/phonograph-issue-tracker#120]
Great job. This player is material design in perfection. But I would like to see a feature to use it on a daily basis. I sing to my songs and all my lyrics are saved within ID3tag of the mp3. Is there a chance to make a feature like to double tap on the artwork in the "now playing" screen to see the lyrics and scroll manually through it. That would be great.﻿

**Comment by arkon** [comment]
You can currently pull up the lyrics in a dialog, so I guess this is sort of resolved. Improving the UI/UX of it would be #220.
