### ISSUE TITLE
Editar tags do perfil do artista manualmente 

### ISSUE THREAD

**Issue by ffrrfelipe** [karimknaebel/phonograph-issue-tracker#121]
Função de editar também as tags do artista, como a biografia e principalmente, a foto do perfil, manualmente no aplicativo. 
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>31</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MPB24.65-34</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>titan_udstv</td></tr>
<tr><td>Device model</td><td>XT1069</td></tr>
<tr><td>Device product name</td><td>titan_retbr_dstv</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
Biographies and art are automatically pulled from a service.

The issue of manually setting an image is logged here: https://github.com/kabouzeid/Phonograph/issues/141
