### ISSUE TITLE
Can't play song

### ISSUE THREAD

**Issue by asherheilbron** [karimknaebel/phonograph-issue-tracker#122]
Every time I tap the notification (it doesn't matter if on the lockscreen or not) the music stops and it says "can't play song". After that occurs I have to skip a song and back to get the song playing again. 
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.2 BETA 1</td></tr>
<tr><td>App version code</td><td>118</td></tr>
<tr><td>Android build version</td><td>9f339bddf2</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MHC19Q</td></tr>
<tr><td>Device brand</td><td>oneplus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>A0001</td></tr>
<tr><td>Device model</td><td>A0001</td></tr>
<tr><td>Device product name</td><td>bacon</td></tr>
<tr><td>Device hardware name</td><td>bacon</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
Does this still happen? I can't reproduce it on my OnePlus One.
