### ISSUE TITLE
Interpreten werden nicht erkannt

### ISSUE THREAD

**Issue by Sturmkraehe1974** [karimknaebel/phonograph-issue-tracker#125]
Hi, 
erstmal zum verwendeten System:
- Android 6.0.1 mit einem Samsung Tab S2
- Musik: MP3 mit ID1 und ID2.4

Habe bereits mehrfach durch Ändern der Tags versucht, dass meine Interpreten richtig erkannt werden (auch bereits die Musik vom Tablet auf SD-Karte verschoben etc.) allerdings ohne Erfolg.
Unter allen neuen Musikstücken im Tab "Interpreten" steht immer <unknown> und auch bei "Alben" steht unter dem Albumnamen <unknown> (auch die Albencover werden nicht angezeigt).
Hat jemand eine weitere Idee, woran das liegen könnte?
Die gleichen Musikstücke werden bei meiner Freundin auf einem HTC One problemlos erkannt.
![screenshot_20160731-150912](https://cloud.githubusercontent.com/assets/20753985/17276739/27672418-5732-11e6-965c-a26ae3988aac.png)
![screenshot_20160731-150917](https://cloud.githubusercontent.com/assets/20753985/17276740/2d1370ec-5732-11e6-94b2-c9d19a1c331f.png)
![screenshot_20160731-151221](https://cloud.githubusercontent.com/assets/20753985/17276741/2d14b3a8-5732-11e6-9317-c0ea6d844a09.png)

**Comment by Sturmkraehe1974** [comment]
Fehler gefunden und korrigiert - das Problem liegt wohl am Zeichensatz bei Android 6.0.1.
Ich habe die App "ID3Fixer" runtergeladen und über alle <unknown> Interpreten laufen lassen (Charset: UTF8) und siehe da, die Interpreten werden alle korrekt angezeigt :-)

**Comment by arkon** [comment]
Glad you got it fixed!

For reference, this is also related to #128.
