### ISSUE TITLE
Artist search bug

### ISSUE THREAD

**Issue by Friiiis** [karimknaebel/phonograph-issue-tracker#126]
Hello 
First off I want to tell how much I love your work with the app. So far I've only got one issue annoying me: when I search for artists, it gives me a number of different results for the same artist, depending on when I uploaded songs from that particular artist. For example: I started uploading 7 song from the band Outlandish. That worked fine. Two weeks later I added another song to my device from the same artist so I now have 8 Outlandish songs. Now when I search for Outlandish in the app, it gives me two results: one artist named Outlandish with 7 songs, and one artist named Outlandish with 1 song.
I have uploaded a screenshot of this below:
http://m.imgur.com/Z8MJaaP

I hope this issue can be fixed. And thank you for an otherwise excellent app.

Gustav
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>31</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>ONE A2003_24_160604</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus2</td></tr>
<tr><td>Device model</td><td>ONE A2003</td></tr>
<tr><td>Device product name</td><td>OnePlus2</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by arkon** [comment]
Do these show up as separate entries in the main artists list too?
