### ISSUE TITLE
c:

### ISSUE THREAD

**Issue by Alan223** [karimknaebel/phonograph-issue-tracker#129]
No es un problema es mas bien una molestia....seria mucho mejor si podrias poner TU la imagen de artista 
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>J700MUBU2APF1</td></tr>
<tr><td>Android release version</td><td>5.1.1</td></tr>
<tr><td>Android SDK version</td><td>22</td></tr>
<tr><td>Android build ID</td><td>LMY48B.J700MUBU2APF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j7elte</td></tr>
<tr><td>Device model</td><td>SM-J700M</td></tr>
<tr><td>Device product name</td><td>j7elteub</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7580</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
What's a TU?
