### ISSUE TITLE
Lock screen player

### ISSUE THREAD

**Issue by RwbyChan2** [karimknaebel/phonograph-issue-tracker#13]
Somehow I can't get a player on my lock screen...
Using:
Huawei P8 Lite
Android 5.0.1
EMUI 3.1

**Comment by karimknaebel** [comment]
what do you mean exactly?

**Comment by RwbyChan2** [comment]
I don't see the music player on my lockscreen while there is music playing. 
This makes me NEED to unlock my phone before I can go to another song, etc

**Comment by karimknaebel** [comment]
There should be a notification with playback controls.

**Comment by RwbyChan2** [comment]
There is a notification in the notificationscreen, but not on the lockscreen

**Comment by karimknaebel** [comment]
Well notifications should show up at the lockscreen on 5.0+

**Comment by RwbyChan2** [comment]
I'm on Android 5.0.1 and it's not showing up, so I wouldn't say that it's fixed, but that might be because the Huawei P8 Lite uses a custom rom (EMUI)

**Comment by karimknaebel** [comment]
It's an issue with your ROM.
