### ISSUE TITLE
Open Question? How to sort albums that were released in the same year?

### ISSUE THREAD

**Issue by paulheising** [karimknaebel/phonograph-issue-tracker#130]
I don't know if this is really a problem of phonograph. Maybe I just need to tag my files the correct way, but I wonder how.

The problem: Some albums of one artist were released in the same year. Let's take as an example the albums "Uno", "Dos", and "Tré" by Green Day. All were released 2012, but actually, "Uno" was released first, then "Dos", and then "Tré".

When I just write "2012" into the year tag, and then go to Phonograph's artist tag, go to Green Day so I see their albums, these three appear in alphabetical order - of course, because the only information which is stored in the tag, is 2012 - so how could they be sorted else?

I tried writting the exact release dates to the year tag, used the pattern YYYY-MM-DD. This did not help. The albums still were not sorted properly.

Do I need to tag my files in a specific way to make Phonograph recognize the exact release date? Or is such detailed sorting not supported yet? If it is not, will this be implemented?

**Comment by srousset** [comment]
I'm not an expert on MP3 tagging (ID3 tags), but my understanding is that the most widespread ID3 standard – version 2.3 – only holds the year. So, if Karim wants to stick to the widespread standard, he'll probably stick to year-only.

Version 2.4 of the ID3 standard allows – but doesn't mandate – a more granular time stamp: it •can• be yyyy-MM or yyyy-MM-dd or some other variants, but it's also allowed to be the traditional yyyy. Version 2.3 remains the most widespread ID3 standard, even though V2.4 was published 16 (sixteeen!) years ago. (Source: http://id3.org)

Best regards, Stéphane

**Comment by paulheising** [comment]
Yeah, I also was really surprised about the fact that ID3V2.4 is so poorly supported...

Windows 7 Explorer doesn't show the tags at all, tagged with mp3tag.

I also tried it for Phonograph, but it does not seem to recognize the year-tag at all. All ID3V2.4 tagged albums are shown with year "0".

But maybe this could also be an android mediascanner issue. Gonna try ID3Fixer on that...

**Comment by arkon** [comment]
ID3v2.4 support is logged in #137, so I'll close this.
