### ISSUE TITLE
Hide albums from album screen

### ISSUE THREAD

**Issue by GRA0007** [karimknaebel/phonograph-issue-tracker#131]
This is a feature request, as I have a few albums on my albums screen that are just mp3 files that got pulled from folders like the sound recorder app and it would be nice if I could hide these by long pressing on them and clicking hide or something in the action bar. 
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.2 BETA 1</td></tr>
<tr><td>App version code</td><td>118</td></tr>
<tr><td>Android build version</td><td>616a640dac</td></tr>
<tr><td>Android release version</td><td>5.1.1</td></tr>
<tr><td>Android SDK version</td><td>22</td></tr>
<tr><td>Android build ID</td><td>cm_kltedv-userdebug 5.1.1 LMY47V 616a640dac test-keys</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>kltedv</td></tr>
<tr><td>Device model</td><td>SM-G900I</td></tr>
<tr><td>Device product name</td><td>cm_kltedv</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by bonjour81** [comment]
I fully agree.
On my side it shows ringtones, notifications and podcasts.

It may be used also something similar to "piktures" ( a photo gallery ): it have a "exclude folders" section in parameters with some defaults excluded folders and possibility to manually add some.

**Comment by arkon** [comment]
You can add a .nomedia file to those folders to prevent them from showing up.
