### ISSUE TITLE
Album shuffle

### ISSUE THREAD

**Issue by jjob1** [karimknaebel/phonograph-issue-tracker#132]
Can you add an album shuffle option ? 

IMO, this is the only important feature your app is missing.

**Comment by paulheising** [comment]
Yes please! I really liked that in poweramp, but this one got too overloaded with features and settings, but the album / folder shuffle option was really nice. 

Phonograph is awesome, but I also miss it, just tapping somewhere and a random album pops up and starts playing (or alternatively could be added to the queue)

**Comment by jjob1** [comment]
Exactly the same thought about Poweramp. 

A dedicated button on the player seem to be perfect (previous/next buttons for songs of the currently played album, and a "shuffle album" button to randomly choose another album). Adding albums to the queue can be awful if you have to press 15 times the "next" button to go to the next album, if you don't want to listen the one that is currently playing.

I know many people listening to their discography by album (in it's entirety) and not by track, making the "shuffle all tracks" option useless and totaly awful when you have a big music collection. All these people use iPods or Poweramp, because they're the only ones to have this feature. I think the album shuffle is a relevant option to add.

**Comment by arkon** [comment]
Sort of a duplicate of #75.
