### ISSUE TITLE
Unable to play any songs

### ISSUE THREAD

**Issue by Recchan** [karimknaebel/phonograph-issue-tracker#134]
Stops when it says listing files
## Device info:

<table>
<tr><td>App version</td><td>0.13.3 BETA 1</td></tr>
<tr><td>App version code</td><td>119</td></tr>
<tr><td>Android build version</td><td>9d78a90330</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>aicp_trltetmo-userdebug 6.0.1 MOB30Z 9d78a90330 test-keys</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>trltetmo</td></tr>
<tr><td>Device model</td><td>SM-N910T</td></tr>
<tr><td>Device product name</td><td>trltetmo</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
Was this still an issue? Were your music files on your external SD card?
