### ISSUE TITLE
Missing biography and pic

### ISSUE THREAD

**Issue by florencedrunk** [karimknaebel/phonograph-issue-tracker#138]
All the info and pic for Florence + The Machine have disappeared. 
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>G920FXXU3DPE9</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29K.G920FXXU3DPE9</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>zeroflte</td></tr>
<tr><td>Device model</td><td>SM-G920F</td></tr>
<tr><td>Device product name</td><td>zerofltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7420</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by arkon** [comment]
This is reliant on Last.fm, but it seems fine to me with a track by Florence + The Machine.
