### ISSUE TITLE
Global toggle to play selected song once (no repeat)

### ISSUE THREAD

**Issue by markreg** [karimknaebel/phonograph-issue-tracker#14]
This option could temporarily suspend automatic playback of the next song in a folder/playlist or song/folder/playlist cycle option.

This is especially useful for e.g. a folder full of lectures where playback of only a single file is desired.

**Comment by karimknaebel** [comment]
I understand what you mean, but Phonograph is not a lecture player, but a music player. There are probably other players which can achieve this behavior. I don't want to clutter Phonograph with lots of options, so I will stick to the basics.
