### ISSUE TITLE
Register media button event receiver

### ISSUE THREAD

**Issue by elmkzgirxp** [karimknaebel/phonograph-issue-tracker#142]
My headphones buttons don't get recognized, yet other apps do. [More info](https://developer.android.com/training/managing-audio/volume-playback.html#PlaybackControls)
## Device info:

<table>
<tr><td>App version</td><td>0.13.3</td></tr>
<tr><td>App version code</td><td>120</td></tr>
<tr><td>Android build version</td><td>eng.ron.20160826.191053</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>aosp_nicki-userdebug 7.0 NRD90M eng.ron.20160826.191053 test-keys</td></tr>
<tr><td>Device brand</td><td>Sony</td></tr>
<tr><td>Device manufacturer</td><td>Sony</td></tr>
<tr><td>Device name</td><td>nicki</td></tr>
<tr><td>Device model</td><td>C1905</td></tr>
<tr><td>Device product name</td><td>C1905</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
See https://github.com/kabouzeid/Phonograph/issues/137 and https://github.com/kabouzeid/Phonograph/issues/148
