### ISSUE TITLE
Lockscreen controls not showing unless [Keep notificaitons on lock screen] option is enabled.

### ISSUE THREAD

**Issue by v7rzlhb3xg** [karimknaebel/phonograph-issue-tracker#145]
Model: Xperia Z3 Compact
Android Version: 6.0.1
Phonograph Version: 0.13.3

Phonograph's lockscreen controls don't show correctly most of the time unless that option's enabled in the Sound & Notification settings. Other music players don't require this option to be enabled to have lock screen controls, is it necessary for Phonograph?

**Comment by arkon** [comment]
Is this still an issue?
