### ISSUE TITLE
Select folders to scan 

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#146]
Manually be able to select folders from which music is shown in the library. 
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>1467354978</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>Intex_Aqua_Ring_V05_India</td></tr>
<tr><td>Device brand</td><td>Intex</td></tr>
<tr><td>Device manufacturer</td><td>Intex</td></tr>
<tr><td>Device name</td><td>Aqua_Ring</td></tr>
<tr><td>Device model</td><td>Aqua_Ring</td></tr>
<tr><td>Device product name</td><td>Aqua_Ring</td></tr>
<tr><td>Device hardware name</td><td>mt6580</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
We rely on Android's media store, so this won't be happening unless we were to switch away from it. The only thing you can really do about it would be to put `.nomedia` files in folders that you don't want to be scanned.
