### ISSUE TITLE
Random song art in notification and recycler views

### ISSUE THREAD

**Issue by Arnav-247** [karimknaebel/phonograph-issue-tracker#152]
In the main recycler views it uses some random images from my sdcard and even in the music notification it shows the random image which is on my sdcard but when i click on the bar to show the playing song the song art is the original one which should be there, i dont know if this is device specific i am using a oneplus one with zephyr rom 6.0.1 just in case if it helps you

**Comment by Arnav-247** [comment]
I could give a logcat if in case you need it

**Comment by arkon** [comment]
I think this is the same as #84.
