### ISSUE TITLE
tags: cover and artist not shown

### ISSUE THREAD

**Issue by Thomas-W72** [karimknaebel/phonograph-issue-tracker#153]
hi,
i transfered files from musicbee on my pc to my android phone (5.1.1). the files on phone contain tags and also cover (cover is also stored in album-folder  on phone), but artist and cover are not shown on phone. enclosed is a hardcopy of the tags from mediainfo. using phonograph 0.13.3
hope that could be fixed ;-)

![correct_tags_not_displayed](https://cloud.githubusercontent.com/assets/5254505/18827998/10a2e994-83d6-11e6-8fa9-7a172007b2b9.png)

**Comment by arkon** [comment]
Is this still an issue? If so, would it be possible to share that file with me somehow?

**Comment by danwin9** [comment]
I have a similar problem the tags on phonograph won't show up correctly in the app and only show up as <unknown artist>. I have a few hundred tracks with this problem. When clicking to change the tags in the tag editor they show up correctly but upon saving them nothing changes. I have included screenshots
![screenshot_20171126-171345](https://user-images.githubusercontent.com/34014462/33246818-3a4bb4fe-d2ce-11e7-9ab8-da3feda5b51e.png)
![screenshot_20171126-171340](https://user-images.githubusercontent.com/34014462/33246819-3a6836e2-d2ce-11e7-8fd5-8284acacdf24.png)
![screenshot_20171126-171351](https://user-images.githubusercontent.com/34014462/33246820-3a8674d6-d2ce-11e7-98d9-9aa9c942ccd3.png)
![screenshot_20171126-171457](https://user-images.githubusercontent.com/34014462/33246821-3ab40afe-d2ce-11e7-93d9-6571d0e6b3c4.png)

**Comment by arkon** [comment]
@danwin9 See https://github.com/kabouzeid/Phonograph/issues/335
