### ISSUE TITLE
FC when on background

### ISSUE THREAD

**Issue by ThallesAraujo** [karimknaebel/phonograph-issue-tracker#156]
App sometimes stops playing when it is in background. Version 0.13.3

**Comment by arkon** [comment]
Does this still happen? We would only be able to look into this if you were to provide logcats.

**Comment by ThallesAraujo** [comment]
I think I found the reason. System Media Server of CyanogenMod/Lineage/RR
crashes when lockscreen media visualization is active. Lock and unlock
screen solves the problem in many of times.

Em seg, 12 de jun de 2017 3:01 PM, Eugene Cheung <notifications@github.com>
escreveu:

**Comment by arkon** [comment]
Alright, so it doesn't seem to be an issue with Phonograph then.
