### ISSUE TITLE
Music stops on device rotation

### ISSUE THREAD

**Issue by anesuccio** [karimknaebel/phonograph-issue-tracker#157]
Hello and thanks for developing this awesome app.
I have an LG G3 running Cyanogenmod 13 (android 6.0.1). The Phonograph app version is 0.13.3. 

When I turn my phone from portrait to landscape mode music stops. This behaviour is quite annoying sometimes, for example in the car.

The app can be more beautiful than it is if you only correct this bug. Thanks.

**Comment by Win7GM** [comment]
## Actually music stops randomly on my device....Device info:

<table>
<tr><td>App version</td><td>0.13.3</td></tr>
<tr><td>App version code</td><td>120</td></tr>
<tr><td>Android build version</td><td>2.1.059_160829</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M dev-keys</td></tr>
<tr><td>Device brand</td><td>ZUK</td></tr>
<tr><td>Device manufacturer</td><td>ZUK</td></tr>
<tr><td>Device name</td><td>z2_plus</td></tr>
<tr><td>Device model</td><td>ZUK Z2131</td></tr>
<tr><td>Device product name</td><td>z2_plus</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

It stops when I'm refreshing outlook, surfing the net with chrome, and when I try to submit bugs

**Comment by arkon** [comment]
@anesuccio @Win7GM Does this still happen? I can't reproduce it on several devices.

**Comment by Win7GM** [comment]
@arkon it just randomly disappeared
Thank you for your time
