### ISSUE TITLE
Glitchy artist/album/song names

### ISSUE THREAD

**Issue by mitmichels** [karimknaebel/phonograph-issue-tracker#158]
The names of the artist, the album and the tracks are incorrect, even though the tags are correct. It only happened to certain tracks from this particular artist, as it can be seen in the screenshots.

Glitchy names: http://i.imgur.com/Eejp2rN.png
Correct tags: http://i.imgur.com/BvC1ZOg.png
The correct artist: http://i.imgur.com/ZlCDjy8.png
The correct album: http://i.imgur.com/493jTvx.png

**Comment by arkon** [comment]
Check out #128 for a potential fix.
