### ISSUE TITLE
An small issue with a String

### ISSUE THREAD

**Issue by pgetsos** [karimknaebel/phonograph-issue-tracker#162]
In billing, pizza option, the apostrophe in the "doesn't" is showing up with the html code (&#39;)
(And the copy of the device info is not good, it copies all the table elements)

 Device info:---
App version 0.13.3
App version code 120
Android build version I9505XXUHOJ2
Android release version 5.0.1
Android SDK version 21
Android build ID LRX22C.I9505XXUHOJ2
Device brand samsung
Device manufacturer samsung
Device name jflte
Device model GT-I9505
Device product name jfltexx
Device hardware name qcom
ABIs [armeabi-v7a, armeabi]
ABIs (32bit) [armeabi-v7a, armeabi]
ABIs (64bit) []

**Comment by arkon** [comment]
This was presumably fixed at some point since I don't see it anymore.
