### ISSUE TITLE
Album art metadata in root of internal storage.

### ISSUE THREAD

**Issue by kkanungo17** [karimknaebel/phonograph-issue-tracker#163]
Whenever I add album art from Last.fm or local gallery or whatever, new metadata files are created in albumthumbs folder in internal storage, and also on the root of internal storage.

This is undesirable, as there are LOT of them, cluttering the storage.

Phone : Lenovo Vibe K5 Plus, Android 5.1.1, Phonograph version 0.13.3

**Comment by arkon** [comment]
Android seems to do this automatically as a caching mechanism. A quick Google search for "albumthumbs" seems like you could delete it, but I'll leave that to your own discretion.
