### ISSUE TITLE
Notification background colour option

### ISSUE THREAD

**Issue by joetancy** [karimknaebel/phonograph-issue-tracker#17]
Would be great if I can force a default background colour in the notifcation shade for tracks without album art.

**Comment by moelle89** [comment]
yeah that really is the big missing feature to make the app run and look perfect, no matter what theme u got applied. - i develop a dark cm12/13 theme, called deep darkness. - there, the notifications got a really dark bg color in combination with almost white texts and titles to grant good readability.

now i got a bunch of users, complaining about unreadable notifications on phonograph ( talking about all tracks without a specific album-cover ) .....for me, its really weird why that elements and text was left out of the awesome color-tinting feature, that manages the fore- & background-color of every track that got some individual album-cover. - if the app allready got such an amazing feature/script included and up working, so please use it even on tracks with no album cover. - i guess it wouldnt take more than a couple of minutes for you, to make the default_album_art and default_artist_image use that great color-tinting method to influence all default-bg and accent colors for notifications. - thats it. it would fix big issue that EVERY dark theme ( with dark notifications ) ...have problem to use that awesome app as great as its intended be used.

btw: i just slightly edited that default album- and artist-pichtures to fit´em to theused colorsheme on my theme. - if other themers do also edit that pictures, it would give you another benefit to use that tinting method on default notifications. - so then, it would look awesome to every theme and provides a perfectly matching bg color! even if the default pictures are edited within the used theme.

**Comment by karimknaebel** [comment]
When there is no album art, I use a transparent background, so I just display the text on top of the frameworks notification background. This is black for KitKat and below and white for Lollipop+. I'll think about applying the default album covers tint to the notification when colored notification is enabled though.

**Comment by moelle89** [comment]
that would be really great! because now its still hardcoded/fixed to the stock android colorsheme , as u mentioned. i havent found a way to touch and change that color of default text and control buttons via all possible method, the cm theme engine offers to modify content. ( or do i miss a value inside of colors.xml, styles.xml or any drawable?  - if that color is not touchable for themers like me, the only way to make your great app work proper, is to change the whole notifications bg color of the theme back to something stocka-like. (white or similar ) but that would destroy the global working, visual experience that i aim to create by using my theme. 

i guess its not only me, there are plenty popular used dark themes that are facing this problematic.

making it dynamic will make your app even more attractive to people who use dark themes. so even more potential user will be satisfiwd by your great music player :-)

**Comment by moelle89** [comment]
oh, sehe gerade erst ich mir mein englisches gestammel auch hätte sparen können :-P

**Comment by karimknaebel** [comment]
@moelle89 Ja und nein, es soll ja für andere lesbar bleiben :) Mein englisch lässt auch noch zu wünschen übrig.

I'm using the `android.R.color.primary_text_default_material_light` and `android.R.color.secondary_text_default_material_light` for the notification content.

Which values do you currently change with your theme, so it does work with other notifications?

**Comment by moelle89** [comment]
@kabouzeid: ich versteh gerade nicht ganz warum es für andere nicht mehr lesbar sein könnte wenn man die notifications dee "cover-losen" tracks ebenso darstellt wie es bereits schon bei allen tracks mit album cover der fall ist.  - einziger änderung die dies rein elementar funktional werden lässt, ist schlicht und ergreifend das default artist-, sowie default-album bild ebebfalls mit der "farbauslese-methode" zu versehen bzw es als zugehörigen content dort miteinzubinden. ( kp wie genau da alles definiert, du weisst es sicherlich :-P )

somit wird der notifications bg nicht mehr als transparentes overlay gesetzt, sondern farblich entsprechend zugehörig zu den von dir erstellten default album- & -artist pics.

und somit is das problem für alle themes mit dunklen notifications aus der welt.

**Comment by karimknaebel** [comment]
@moelle89 das hatte ich schon verstanden, ich meinte auch nur, dass das was wir hier schreiben auch für andere lesbar sein sollte, aber ist ja jetzt auch egal ^^

**Comment by karimknaebel** [comment]
@moelle89 es würde mich trotzdem interessieren, wie genau du die notifications von anderen apps "themest".

**Comment by moelle89** [comment]
@kabouzeid  dann muss der werte herr bitte meine hangouts einladung annehmen. da stehe ich dir dann gerne rede und atnwort :-P

**Comment by robnjo2112** [comment]
@kabouzeid please add such a feature. I'm using a jellybean ROM (material themed) and the notification bg is white. it makes the text unreadable unless enabling tinted notification color(if there is album image).
There are a lot of people using such material themed KitKat and jb ROMs facing this issue

I'm not able to decode the package properly with my SDK and framework. I'm also not sure how to solve this though

**Comment by arkon** [comment]
"Fixed" this by setting the default background to white instead of assuming what colour it is based on Android version (https://github.com/kabouzeid/Phonograph/pull/199).
