### ISSUE TITLE
Blank album art on "Now Playing" and all lists

### ISSUE THREAD

**Issue by saadeghi** [karimknaebel/phonograph-issue-tracker#170]
All my songs have album arts but when I skip a few songs on "Now Playing" page, only the current song's and the next song's album art shows up and all following songs shows a black screen. This issue fixes when I switch to another app and switch back to phonograph.

I also have the same issue on lists (albums, songs, etc). When I'm scrolling through the list, only tge first visible area show their album arts and all other songs are blank. This also fixes when I switch between another app.

I have Android 7.1 CM14.1 OnePlus One

**Comment by arkon** [comment]
Hmm, I can't reproduce this on my OnePlus One running LineageOS 14.1 (7.1.1). Is this still happening for you?

**Comment by saadeghi** [comment]
Actually I haven't seen the issue since I updated to new version.  
Thanks for this great app.
