### ISSUE TITLE
Scrolling lag caused by artist cover

### ISSUE THREAD

**Issue by lucaxvi** [karimknaebel/phonograph-issue-tracker#171]
When scrolling through the artists' list I get heavy lag as soon as a certain artist cover (for xThe Killers") loads up.

**Comment by lucaxvi** [comment]
Device info:
---
<table>
<tr><td>App version</td><td>0.13.3</td></tr>
<tr><td>App version code</td><td>120</td></tr>
<tr><td>Android build version</td><td>36</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MPI24.65-33</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>osprey_umts</td></tr>
<tr><td>Device model</td><td>MotoG3</td></tr>
<tr><td>Device product name</td><td>osprey_vfeu</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
Being tracked in https://github.com/kabouzeid/Phonograph/issues/174.
