### ISSUE TITLE
Unable to delete track from external SD

### ISSUE THREAD

**Issue by praneetrohida** [karimknaebel/phonograph-issue-tracker#172]
Whenever i delete any song which is stored on external device, it disappears from phonograph but is still there when i check it through file manager. Please fix this delete from device feature soon as i dont want to switch away from my favorite music app.

**Comment by Gyoo** [comment]
I have the same issue, a fix would be welcome.

**Comment by arkon** [comment]
Related to external SD card permissions discussed in #101.
