### ISSUE TITLE
Add ReplayGain support

### ISSUE THREAD

**Issue by jgandert** [karimknaebel/phonograph-issue-tracker#175]
Especially considering todays [loudness war](https://en.wikipedia.org/wiki/Loudness_war) it's vital to have a way to normalize loudness. [ReplayGain](https://en.wikipedia.org/wiki/ReplayGain) is the current [widely used standard](https://en.wikipedia.org/wiki/ReplayGain#Implementations) to achieve that.

**Comment by slock83** [comment]
Came here to say the exact same thing ! 
(And to say this app is awesome, too !)

**Comment by Sirove** [comment]
+1!
With ReplayGain support this app would be just perfect!

**Comment by arkon** [comment]
Tracked in https://github.com/kabouzeid/Phonograph/issues/259
