### ISSUE TITLE
[feature Request] Change default music folder

### ISSUE THREAD

**Issue by fabermundi** [karimknaebel/phonograph-issue-tracker#176]
It would be nice if I can select the default music folder.
When starting the app in the folder view it automatically shows the "Music" folder on the internal storage but this is not my default for my music.
I have my music on my SD card so I always have to switch the folder when starting the app.
So it would be nice if I could change the default music folder.

**Comment by arkon** [comment]
There's a "Set as start directory" option in the overflow menu for a folder that you can use for this.
