### ISSUE TITLE
Cannot play .wma files

### ISSUE THREAD

**Issue by Rinnosuke93** [karimknaebel/phonograph-issue-tracker#180]
As the title states, whenever the app ends up over a .wma file audio, a pop-up message saying the file cannot be opened shows up. Is it a bug or does the app still lack support to said format?

Here the information the app copied automatically:

Device info:
---
<table>
<tr><td>App version</td><td>0.13.5</td></tr>
<tr><td>App version code</td><td>124</td></tr>
<tr><td>Android build version</td><td>WW_Phone-13.0.1.33-20161022</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MRA58K.WW_Phone-13.0.1.33-20161022</td></tr>
<tr><td>Device brand</td><td>asus</td></tr>
<tr><td>Device manufacturer</td><td>asus</td></tr>
<tr><td>Device name</td><td>ASUS_X008</td></tr>
<tr><td>Device model</td><td>ASUS_X008D</td></tr>
<tr><td>Device product name</td><td>WW_Phone</td></tr>
<tr><td>Device hardware name</td><td>mt6735</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by arkon** [comment]
Android doesn't support WMA files natively, unfortunately. Some apps that implement their own codecs like VLC or PowerAmp should work, or you can convert them to a different format.
