### ISSUE TITLE
Status bar too big

### ISSUE THREAD

**Issue by jajube** [karimknaebel/phonograph-issue-tracker#181]
The status bar appears too big when I'm on the main screen of the app. It doesn't occur when I'm on other screens like "notify a problem".
Screenshot:
![sin titulo](https://cloud.githubusercontent.com/assets/17009744/21729010/74af27b8-d449-11e6-8df3-ecbf66188af0.jpg)

Device info:
---
<table>
<tr><td>App version</td><td>0.13.5</td></tr>
<tr><td>App version code</td><td>124</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.MAGMIDI</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MXB48T</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>capricorn</td></tr>
<tr><td>Device model</td><td>MI 5s</td></tr>
<tr><td>Device product name</td><td>capricorn</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by arkon** [comment]
Should be fixed by https://github.com/kabouzeid/Phonograph/pull/128
