### ISSUE TITLE
Equalizer not found

### ISSUE THREAD

**Issue by prateeknischal** [karimknaebel/phonograph-issue-tracker#186]
Trying to open equalizer, but toasts "No Equalizer found".

OS : Oxygen 4.0.2 on Android 7.0
Build : ONEPLUS A3003_16_170114
![screenshot_20170126-135616](https://cloud.githubusercontent.com/assets/5807820/22324536/f65abbac-e3cf-11e6-926a-33d7efed3195.png)

**Comment by arkon** [comment]
That means your ROM doesn't have an equalizer. You can also try installing one from the Play Store.
