### ISSUE TITLE
Wrong Notification Content

### ISSUE THREAD

**Issue by timjtech** [karimknaebel/phonograph-issue-tracker#187]
Device info:
---
<table>
<tr><td>App version</td><td>0.13.5</td></tr>
<tr><td>App version code</td><td>124</td></tr>
<tr><td>Android build version</td><td>857212.3</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M release-keys</td></tr>
<tr><td>Device brand</td><td>htc</td></tr>
<tr><td>Device manufacturer</td><td>HTC</td></tr>
<tr><td>Device name</td><td>htc_pmewl</td></tr>
<tr><td>Device model</td><td>HTC 10</td></tr>
<tr><td>Device product name</td><td>pmewl_00617</td></tr>
<tr><td>Device hardware name</td><td>htc_pme</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

When selecting next track, the previous track information occasionally displays instead, and then lags one track behind of the currently playing songs.

**Comment by timjtech** [comment]
http://www.dumpt.com/img/viewer.php?file=plbudjti7yba8zusdlzj.png

**Comment by arkon** [comment]
Does this still occur in the latest version?
