### ISSUE TITLE
Bugs and Features

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#19]
Phonograph version: 0.11.0 RC
Android 6.0.1 
Nexus 6P

I have been using this app for half a year now and down below are some bugs and some features, that might be missing.

**Bugs**:
- (this is probably due to the android media store) - If a file/artist/title starts with "The" (for example: The Who - Wont Get Fooled Again), the file is not listed under T but under W.
  Some other players have solved this issue by adding the "sort from A-Z" next to the automatic system where the "The-issue" occurs.
- Sometimes there are no play/pause/next/previous buttons in the widget in the notification bar. The invisible "symbols" are still clickable though. The same happened two times with the same symbols but in-app. Unfortunately I dont know how to reproduce this.

**Features**:
- If a song with a long title/filename is playing, it is always shortened with three dots (f.e.: The Who - Wont Get Foo...) - It would be a nice addition, if the rest of the name would also slide in (like it does in google play music for example). This "sliding in" is missing in-app as well as in the widget in the notification bar. 
- I know one can turn off the album cover art. It would be nice if there was an option to turn off the images for interprets aswell. It would be nice if the option is given to the user whether he wants to use it or not.
- google Now (voice) support. Would be a nice add on, if the app could play music via voice command (play my music) through google now. There are a few players supporting this. Would be great to see phonograph on the list too.

**Comment by karimknaebel** [comment]
Hey, please open a separate issue for every bug and feature.

Also, I can tell you right now the "The-issue" isn't a bug and won't fix. I know that there a different opinions out there about how it should be.

What do you mean with "turn of album cover art"?

I'll answer the other things when you've opened a separate issue for them :)
Thx for your feedback!
