### ISSUE TITLE
Favorites playlist loses entries

### ISSUE THREAD

**Issue by ridcully99** [karimknaebel/phonograph-issue-tracker#194]
Several times I added songs to favorites playlist, but a few days later they are gone and the list is empty.

Device info:
---
<table>
<tr><td>App version</td><td>0.13.5</td></tr>
<tr><td>App version code</td><td>124</td></tr>
<tr><td>Android build version</td><td>3636322</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NOF26V</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>sailfish</td></tr>
<tr><td>Device model</td><td>Pixel</td></tr>
<tr><td>Device product name</td><td>sailfish</td></tr>
<tr><td>Device hardware name</td><td>sailfish</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by ridcully99** [comment]
For me its the same with favorites. I created issue #194 for this.

**Comment by filippobistaffa** [comment]
I also noticed that favorites disappear

**Comment by HeyItsJono** [comment]
Having this same issue, along with #195 
Version 0.15.0 of Phonograph on a Stock 7.1.2 Nexus 6P.
Playlists physically saved to a file on the internal storage will remain, but those just created in Phonograph and not saved as a file, along with the Favourites playlist itself, will always eventually wipe.

**Comment by arkon** [comment]
https://github.com/kabouzeid/Phonograph/issues/394
