### ISSUE TITLE
Playlists disappear

### ISSUE THREAD

**Issue by francescobaldan** [karimknaebel/phonograph-issue-tracker#195]
Some days after I create a music playlist, it disappear, and the "Playlist" fragment only shows the default playlists (Recently added, History and Favourites)

Device info:
---
<table>
<tr><td>App version</td><td>0.13.5</td></tr>
<tr><td>App version code</td><td>124</td></tr>
<tr><td>Android build version</td><td>3635581</td></tr>
<tr><td>Android release version</td><td>7.1.2</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NPG05D</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>bullhead</td></tr>
<tr><td>Device model</td><td>Nexus 5X</td></tr>
<tr><td>Device product name</td><td>bullhead</td></tr>
<tr><td>Device hardware name</td><td>bullhead</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by ridcully99** [comment]
For me its the same with favorites. I created issue #194 for that.

**Comment by arkon** [comment]
https://github.com/kabouzeid/Phonograph/issues/394
