### ISSUE TITLE
Feature Request : Music player notification

### ISSUE THREAD

**Issue by Gagandeep39** [karimknaebel/phonograph-issue-tracker#197]
It would be really nice if you think of increasing the dimensions of Play / pause button in music player notification...I really liked the new notification after the update but the buttons appear to be really small...Why not just make the play / pause button of it slightly bigger than the other 2 buttons ( used for changing tracks ) just like Google play music

**Comment by arkon** [comment]
The hit boxes are the same as Google Play Music's since it's just a standard media notification. There's an internal fix that lets you use the old notification instead if that's preferable, so that'll be available soon.
