### ISSUE TITLE
Warn if the song is already in the playlist before adding it

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#2]
Have playlists warn you if the song being added is already in it.  Also the option to search playlists for specific songs would be of great use to many (especially with large playlists).

**Comment by karimknaebel** [comment]
Playlist are supposed to be able to contain songs more than one time.
I don't see why searching in a playlist is necessary too. I think you can just use the normal search for that.
Thanks for your feedback however!

**Comment by ghost** [comment]
Searching throughout the entire library rather than playlist would be more than adequate if the searcher is only looking to find a song to listen to, but for the sake of playlist management (especially since there's no option to alphabetize playlists) it would be a smart feature to be able to search playlists to remove songs (even moreso if it's an enormous playlist and you're trying to quickly remove a few that have been decided unsuitable).

Also to clarify, earlier when I said to warn before adding a song twice to a playlist, I meant to the same playlist, not different ones. That is because the vast majority of people (me included) accidentally add songs more than once to the SAME playlist because there's no prompt alerting us if the song is already in the playlist (and we've forgotten it's the song has been added before). Since playlists cannot be alphabetized or searched, they can become very clunky with unwanted dupes of songs. These dupes can be especially hard to detect if the playlist has 100+ songs.  This is the reasoning behind searching playlists and the prompt before adding a song to the same playlist twice.

Even if these were disabled by default only to be enabled in settings that would save so much time on people with heavy playlists. Please tell me you can see my point of view.

**Comment by jonaylstock** [comment]
*I said playlists CAN be alphabetized or searched but I meant CANT.

**Comment by karimknaebel** [comment]
@jonaylstock makes sense now. However I don't think I'll add that search feature soon. The warning prompt is a good idea.

PS: for the future: please only one request/bug per issue.

**Comment by arkon** [comment]
Tracked in https://github.com/kabouzeid/Phonograph/issues/109.
