### ISSUE TITLE
When a title is too long, slide in the entire title instead of showing the three dots 

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#20]
Android 6.0.1
Nexus 6P
0.11.0 rc Version

If a song with a long title/filename is playing, it is always shortened with three dots (f.e.: The Who - Wont Get Foo...) - It would be a nice addition, if the rest of the name would also slide in (like it does in google play music for example). This "sliding in" is missing in-app as well as in the widget in the notification bar.

**Comment by karimknaebel** [comment]
AFAIK it won't work with the notification and widget due to API limitations.

**Comment by arkon** [comment]
Duplicate of #70
