### ISSUE TITLE
Order of play in Albums 

### ISSUE THREAD

**Issue by r14balu** [karimknaebel/phonograph-issue-tracker#204]
When I play the first song in an album, the order of play is shuffled and it's never in the order it's meant to be in the album. 
Please fix this.

**Comment by arkon** [comment]
Are you in shuffle mode?

**Comment by r14balu** [comment]
Yes, I was in shuffle mode. That's why it happened.
Apparently, everytime I shuffle the entire library, every album plays in
shuffle mode. Fix it if possible

Thank you.

**Comment by arkon** [comment]
You just need to turn off shuffle if that happens, it's not a bug.
