### ISSUE TITLE
Most songs are shown but don't play. 

### ISSUE THREAD

**Issue by ashishmahla** [karimknaebel/phonograph-issue-tracker#206]
This thing first started as problem with few songs but now it has grown bigger. Many of the songs on my device are shown in various places like Playlists but when i click play button it shows "Can't play this song" or smth like that. Also i have checked that there is no problem with songs by playing them in another player. Moreover, it it can't play songs then it should skip and play next one. But there is no such feature hence i have to waste a lot of time clicking next and finding smthing that plays. Plz fix this bcoz i love phonograph a lot.

**Comment by arkon** [comment]
Are these tracks on your external SD card?

**Comment by ashishmahla** [comment]
Yes most of them are. Come to think of it the internal memory songs have no
issue.

On Jun 13, 2017 00:07, "Eugene Cheung" <notifications@github.com> wrote:

Are these tracks on your external SD card?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kabouzeid/phonograph-issue-tracker/issues/206#issuecomment-307880017>,
or mute the thread

**Comment by arkon** [comment]
@ashishmahla Thanks. I'll close this in favour of #101, which is also an issue about playing tracks off of an external SD card.
