### ISSUE TITLE
Widget design improvements

### ISSUE THREAD

**Issue by moonmehta** [karimknaebel/phonograph-issue-tracker#208]
If they are more solid, material like, maybe synced with your theme, it would be awesome

**Comment by moonmehta** [comment]
Device info:
---
<table>
<tr><td>App version</td><td>0.14.1</td></tr>
<tr><td>App version code</td><td>129</td></tr>
<tr><td>Android build version</td><td>19af251082</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>lineage_surnia-userdebug 7.1.1 NOF27B 19af251082</td></tr>
<tr><td>Device brand</td><td>Motorola</td></tr>
<tr><td>Device manufacturer</td><td>Motorola</td></tr>
<tr><td>Device name</td><td>surnia_uds</td></tr>
<tr><td>Device model</td><td>XT1521</td></tr>
<tr><td>Device product name</td><td>Moto E LTE (2nd gen)</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
Done in https://github.com/kabouzeid/Phonograph/pull/225
