### ISSUE TITLE
Manually edit artist images

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#21]
Android 6.0.1 
Nexus 6P 
0.11.0 rc 

I know one can turn off the album cover art. It would be nice if there was an option to turn off the images for interprets aswell. 
I have uploaded a screenshot. 
There are no covers for titles, albums, genres etc. But there are images for interprets/artists which neither can be turned off nor deleted. 

I know there are options to turn off the cover art Downloads, but certainly this setting does not affect the interpret/artists menu, but only the album menu

**Comment by karimknaebel** [comment]
Album covers are never automatically downloaded at all. Artist covers are only downloaded via WiFi by default. You can set this to "never" in the settings too. There is currently no way to delete already downloaded artist images. The only option would be to set the download option to wifi and the clear the apps cache.

**Comment by karimknaebel** [comment]
The option to delete artist images will be included in the upcoming feature to generally edit artist images manually.
