### ISSUE TITLE
Year doesn't show properly for FLAC files (returns a 0)

### ISSUE THREAD

**Issue by elmkzgirxp** [karimknaebel/phonograph-issue-tracker#213]
Device info:
---
<table>
<tr><td>App version</td><td>0.15.0 BETA 1</td></tr>
<tr><td>App version code</td><td>130</td></tr>
<tr><td>Android build version</td><td>5ff33e4153</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NOF27C</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus3</td></tr>
<tr><td>Device model</td><td>ONEPLUS A3000</td></tr>
<tr><td>Device product name</td><td>aosp_oneplus3</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by arkon** [comment]
Duplicate of https://github.com/kabouzeid/Phonograph/issues/121
