### ISSUE TITLE
Duplicate songs

### ISSUE THREAD

**Issue by coolis666** [karimknaebel/phonograph-issue-tracker#214]
i can't find a way to stop them showing. i restarted my phone, unmounted and mounted sd card but nothing worked. phone moto g3

**Comment by coolis666** [comment]
Device info:
---
<table>
<tr><td>App version</td><td>0.14.1</td></tr>
<tr><td>App version code</td><td>129</td></tr>
<tr><td>Android build version</td><td>14</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MPIS24.107-55-2-12</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>osprey_u2</td></tr>
<tr><td>Device model</td><td>MotoG3</td></tr>
<tr><td>Device product name</td><td>osprey_reteu_2gb</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
Sounds like an issue with the media store. Do duplicates show up in other music player apps as well?

**Comment by coolis666** [comment]
Other music players were ok... I couldn't avoid clearing the media storage because no one answered for weeks and it worked for me. Now all my songs are single. Anyway thanks for answering even a month late 😃

**Comment by arkon** [comment]
Sorry about that. :(

**Comment by coolis666** [comment]
no worries, have a nice day
