### ISSUE TITLE
Two toolbar instead of one

### ISSUE THREAD

**Issue by cioccarellia** [karimknaebel/phonograph-issue-tracker#217]
In the player/artist activity there are 2 toolbars that can be merged in one, to save space on low resolution devices
![screenshot_20170429-143913](https://cloud.githubusercontent.com/assets/23010471/25555553/e8d1a96a-2ce9-11e7-9ff7-7a275d9e3267.png)

**Comment by arkon** [comment]
Duplicate of #106
