### ISSUE TITLE
Google Now Support

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#22]
Android 6.0.1 
Nexus 6P 
0.11.0 rc 

Google Now (voice) support. Would be a nice add on, if the app could play music via voice command (play my music) through google now. There are a few players supporting this. I have uploaded a screenshot for further clarification - Would be great to see phonograph on the list to set as default player in G Now
![screenshot_20160424-161648](https://cloud.githubusercontent.com/assets/18641304/14768104/4cf16348-0a38-11e6-8bd6-6cb281930bbb.png)

**Comment by karimknaebel** [comment]
It's working for me if I hit the three dot menu right next to "Musik abspielen mit..."

**Comment by karimknaebel** [comment]
Goto Google app. Goto settings, goto phone search, disable play music. Use OK Google to play a song, select the player.

If you don't do that before, the Google app will always use Play Music.
