### ISSUE TITLE
Widget album artwork shows photo

### ISSUE THREAD

**Issue by dfunstufff** [karimknaebel/phonograph-issue-tracker#227]
Widget shows my photos as album artwork instead of the artwork itself.

**Comment by arkon** [comment]
@danny-funstufff Does this always happen? Do the albums that show up with the photos also do that somewhere in the main app too?

**Comment by dfunstufff** [comment]
It happens rarely, I think only when the app has not been used for quite a while. The photos only appear on the widget, not the main app.
![wechat image_20170616082600](https://user-images.githubusercontent.com/20161336/27206944-7cf3a442-526d-11e7-80ce-ccc0a4de5c1c.jpg)

**Comment by arkon** [comment]
Can you just double check if going to the artist, then viewing the albums list there shows the wrong photo too? It's something that I've personally experienced before too so I'm wondering if it's the same for you too.

**Comment by arkon** [comment]
I can confidently say that it's an issue with the Android media store though, since it seems to have happened for people using other music players too.

**Comment by dfunstufff** [comment]
yeah, going to the artist, it shows the wrong photo too. I see, thanks for responding!

**Comment by arkon** [comment]
Thanks for checking. I'll close this since it's a duplicate of #84.
