### ISSUE TITLE
Some albums the song order is ignored

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#228]
I'm loving this app, but there are some albums that I have in which all the songs are numbered correctly, but Phonograph puts them out of order anyway. Sometimes it's just one song, other times it's a few, but I can't seem to fix it by editing the tags or by deleting and re-adding the music. An example is attached here, but it's happening with several albums. 
![screenshot_20170616-212057](https://user-images.githubusercontent.com/29496943/27250084-0f912060-52da-11e7-9595-4d17045208a6.png)

**Comment by arkon** [comment]
I'm assuming that the track numbers that you have are just "3", "1", "2", etc.? The only proper reason that they might appear like this would be that they're on different discs (i.e. the first track there is on the first disc, but everything else is on the second disc).
