### ISSUE TITLE
Wrong album covers loaded for some songs

### ISSUE THREAD

**Issue by skameechka** [karimknaebel/phonograph-issue-tracker#23]
Application puts  photos of Marcus Mumford to the few random songs instead normal album cover in the notification bar and song search. And this problem is only in your app.  Meizu m2 note,  android 5.1
App version 0.11.0 rc

**Comment by skameechka** [comment]
I could place some screenshots But I can't understand where to add them

**Comment by karimknaebel** [comment]
Sorry, I don't quite understand what you mean.

Btw: You can attach pictures when you comment on this issue from the desktop version of the site :)

**Comment by skameechka** [comment]
![s60424-235106](https://cloud.githubusercontent.com/assets/18648398/14774213/4043756c-0abc-11e6-8597-d4b5e30cc524.jpg)
![s60424-235118](https://cloud.githubusercontent.com/assets/18648398/14774218/480fb404-0abc-11e6-9145-c230cf7b4cd0.jpg)
![s60424-235124](https://cloud.githubusercontent.com/assets/18648398/14774222/4ce4675e-0abc-11e6-95b2-d3b0e6e75d7e.jpg)
There is a huge mess in album covers

**Comment by arkon** [comment]
I _think_ this is the same thing as #84.
