### ISSUE TITLE
Add Artist images manually

### ISSUE THREAD

**Issue by soumikbhatta** [karimknaebel/phonograph-issue-tracker#232]
Please add a feature to add artist  images manually from gallery/file explorer.
Downloading artist images from app is very data consuming,which fails most of the times.  

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by arkon** [comment]
Duplicate of https://github.com/kabouzeid/Phonograph/issues/141

**Comment by soumikbhatta** [comment]
@arkon when are we going to get the feature

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by arkon** [comment]
@Soumikbhatta I don't think this is a really high priority thing right now. Development depends on people's free time too, so there isn't any set timelines.
