### ISSUE TITLE
Displaying birate for VBR files

### ISSUE THREAD

**Issue by andiandi13** [karimknaebel/phonograph-issue-tracker#233]
Hi,

I see that Phonograph is displaying the average bitrate for MP3s variable bit rate (VBR) files. 

May I ask how you did it since the bitrate isn't inside the mp3 header ?

Thanks

**Comment by arkon** [comment]
We just get it from the header using [JAudiotagger](http://www.jthink.net/jaudiotagger/). You can see it in [the source code](https://github.com/kabouzeid/Phonograph/blob/master/app/src/main/java/com/kabouzeid/gramophone/dialogs/SongDetailDialog.java#L98).
