### ISSUE TITLE
Cannot delete from device

### ISSUE THREAD

**Issue by pholls** [karimknaebel/phonograph-issue-tracker#239]
When I try to delete a track, after finding it in Phonograph and clicking "delete from device", the track will reappear in my library after some time.

**Comment by arkon** [comment]
Is it on your internal or external SD card?

**Comment by pholls** [comment]
External SD card

**Comment by arkon** [comment]
Unfortunately, this is a known issue. It's being tracked here: https://github.com/kabouzeid/Phonograph/issues/94

**Comment by pholls** [comment]
Ah, I couldn't find that before. Thanks!
