### ISSUE TITLE
Songs should play next in the order you pick them

### ISSUE THREAD

**Issue by jaxbulsara** [karimknaebel/phonograph-issue-tracker#24]
For example, I'm playing all of my songs on shuffle, and I want to play Uptown Funk next, so I click "play next" on it. Then I feel like playing a couple songs, Hello and I Can't Feel My Face, after Uptown. I want to click play next on those two and have them automatically queue up after Uptown Funk. After these three songs finish, the queue should go back to shuffling all of my songs.

**Comment by karimknaebel** [comment]
No, this is not what "play next" is supposed to do.
