### ISSUE TITLE
[Suggestion] Disable shuffle when playing an Album 

### ISSUE THREAD

**Issue by r14balu** [karimknaebel/phonograph-issue-tracker#241]
When a song is picked and player from an album, the next song that's player is always from the shuffle playlist. 
My suggestion is to play the next song from the album instead. (Only when playing from an album)

**Comment by arkon** [comment]
If you select a song from the album view, it should just play that album. The songs might be shuffled if you were previously in shuffle mode, but you can turn that off and it'll go back to the album's ordering.

Are you seeing something different?

**Comment by r14balu** [comment]
My point is you shouldn't have to disable the shuffle everytime you listen
to an album. The app must automatically switch off shuffle when an album is
played.
That's how pretty much every music app works like. Just a suggestion.

**Comment by arkon** [comment]
Fixed by https://github.com/kabouzeid/Phonograph/pull/527

**Comment by nordaviento** [comment]
God I thought I was the only one, it's plain stupid not to have this option automatically, I always forget to turn shuffle off and thus end up playing the album in the wrong order
