### ISSUE TITLE
[Suggestion] Built-in Chromecast/Chromecast Audio support

### ISSUE THREAD

**Issue by tysox** [karimknaebel/phonograph-issue-tracker#248]
I'm not sure if this is possible, given that Chromecasts generally stream from the Internet, but in-app support to cast music to a Chromecast/Chromecast Audio would be greatly appreciated.

(N.B. As opposed to casting everything from your device)

**Comment by arkon** [comment]
Duplicate of https://github.com/kabouzeid/Phonograph/issues/64
