### ISSUE TITLE
Integrated equalizer

### ISSUE THREAD

**Issue by vishalkhedkar** [karimknaebel/phonograph-issue-tracker#25]
Phonograph would undoubtedly win the best design award among all the music players out there, but since I have had an Android device (5 years now), I have not found any music player with an equalizer as great as that of Poweramp. 

If Phonograph is able to get an equalizer even close to that, I will look nowhere else and make it my primary music player. 

The clarity and depth of bass is just unmatched in Poweramp. Would be great if the developer could figure out a way to implement that. 

And awesome work BTW, wish I could be like you.

**Comment by karimknaebel** [comment]
try this one https://play.google.com/store/apps/details?id=eu.pinpong.equalizer

**Comment by arkon** [comment]
Duplicate of https://github.com/kabouzeid/Phonograph/issues/96
