### ISSUE TITLE
Year tag isn't displayed correctly for FLAC files.

### ISSUE THREAD

**Issue by WRob90** [karimknaebel/phonograph-issue-tracker#251]
See picture. The Year is displayed correctly when the files are mp3 but not flac. It just says 0.

![screenshot_20171017-230314_resized_20171017_110339853](https://user-images.githubusercontent.com/32871704/31665247-b5c91f9e-b38f-11e7-93e0-7879cf73d3dc.png)

**Comment by arkon** [comment]
Duplicate of https://github.com/kabouzeid/Phonograph/issues/121
