### ISSUE TITLE
Vignette & Menu Upon Closing/Reopening

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#252]
I can easily toggle this display by clicking on the album art, fantastic!  However when I close Phonograph from recent apps, then open up again, the menu / vignette / heart reappear;

Could you please make this toggle hold even when closing the app / rebooting, it is annoying to have to keep pressing it off each time I open phonograph.

Thank you,
Jay

![screenshot_20171031-175412 1](https://user-images.githubusercontent.com/9422695/32240221-ae2b39cc-be64-11e7-8196-0ba415d7e06a.jpg)

**Comment by arkon** [comment]
This is definitely something that we want to do: https://github.com/kabouzeid/Phonograph/issues/297
