### ISSUE TITLE
Lockscreen pause button's "hitbox" isnt aligned correctly with the button on my device

### ISSUE THREAD

**Issue by AgathoN** [karimknaebel/phonograph-issue-tracker#259]
Steps to reproduce:
- start phonograph and start a song
- lock the device
- wake it up so its on the lockscreen
- press pause button in the middle

It rarely works for me. Here is what happens when I click it 10 times in a row when playing a song.
1. track restarts (registered left button - rewind)
2. registers pause
3. instead of resuming play it starts with the next track +1
4. restarts that +1 song
5. pause
6. instead of resuming play it starts with the next track +2
7. restarts that +2 song
8. pause
9. instead of resuming play it starts with the next track +3
10. I hit the button multiple times now and the whole app freezes - phonograph does not respond - I click wait and it works fine again

Device is a Xiaomi Redmi Note 4 on Android 7.0 NRD90M with MIUI tagged onto it by the manufacturer MIUI Global 9.5.8.0 NCFMIFA. The phone has a 5,5 inch FHD display

I am not sure if the lockscreen widget is part of the android version or the music player app so I tried ET Music Player Pro V 2017.0.1 which also has a lockscreen widget - no issues. The build in MI Music app also doesnt have misaligned buttons.

**Comment by arkon** [comment]
Can you post a screenshot too?

**Comment by arkon** [comment]
That's MIUI, unfortunately. Other ROMs usually just show the actual notification on the lockscreen.

**Comment by AgathoN** [comment]
Hm, then why does ET Music Player Pro not have this issue? Thats a bit confusing...

**Comment by arkon** [comment]
It has its own lockscreen that overrides the system's. You'll see this lockscreen if you use something like Google Play Music too.
