### ISSUE TITLE
Simple Last.fm scrobbler stops scrobbling randomly.

### ISSUE THREAD

**Issue by Almostbloop** [karimknaebel/phonograph-issue-tracker#261]
The app seems to stop scrobbling randomly for periods of time (between 12h-72h so far). Not sure what causes to happen/stop. 

This started happening a week ago after I re-installed the app. I have uninstalled and reinstalled the app since but that didn't solve the problem.

I use google play music with a Huawei P10 Lite

**Comment by arkon** [comment]
Is this supposed to be an issue for Simple Last.fm Scrobbler? This is the Phonograph repo.

**Comment by Almostbloop** [comment]
My bad, not sure how I got here... thanks for letting me know
