### ISSUE TITLE
F-Droid?

### ISSUE THREAD

**Issue by stephendore** [karimknaebel/phonograph-issue-tracker#27]
Hi, just wondering are there any plans to bring Phonograph to F-Droid? I am trying to go Google free and this is one of the last apps I regularly use that relies on the Play Store for updates!

Sorry if this is not the correct place to put a question like this.

**Comment by karimknaebel** [comment]
No, I don't want to update the app at different places. You can subscribe to Phonograph on APKMirror :)

**Comment by stephendore** [comment]
Ahh OK, thanks for your quick response! I'll do that
