### ISSUE TITLE
Sorting options

### ISSUE THREAD

**Issue by SaviDaWavi** [karimknaebel/phonograph-issue-tracker#29]
I enjoy the song organizer feature found in black player and would like it to be in phonograph. I use the sort artist A-Z feature which keeps the album songs in the proper order with the artists being alphabetized.

**Comment by nspacedust** [comment]
Yeah it will be good if you add this feature

**Comment by rednaxela-work** [comment]
I'd also like a "sort by year" option (ascending and descending) to be able to sort albums (all albums or all albums of an artist). 

And for the artist view it'd be nice to be able to sort all songs by album or year - also ascending and descending; not only alphabetically as is the default.

**Comment by paulheising** [comment]
I think, in the ALBUMS Tab, some grouping by Artist would be nice.

**Comment by paulheising** [comment]
I just realized, that in the ARTISTS tab, artists names starting with "The", the "The" is discarded for sorting, and they are being sorted with their second word.

So "The Birds Of Satan" are being sorted as if the artist name started with a B, not with a T.

This is good.

It would be nice, if this could be extended for german artists, starting with "Die" as well. So, "Die Ärzte", "Die toten Hosen", or "Die fantastischen Vier" would not be sorted in under D, but under A, T and F instead.
