### ISSUE TITLE
Incorrect Character Display

### ISSUE THREAD

**Issue by yurisuika** [karimknaebel/phonograph-issue-tracker#31]
0.11.0 RC / 0.13.0 BETA 2
Android 6.0.1
SM-N920P

In the list of artists, the artist Peu Être is displayed as Peu Ętre, whereas where the character is found within album titles it is displayed correctly.  As such, fetching image and biography fails.  Additionally, several albums are split in two as if some tracks lack album artist names.  However, this is not the case.  All locations where the artist name is displayed are incorrect (now playing, notification, even third party widgets).

http://s32.postimg.org/dr11kdrck/Screenshot_20160427_184119.jpg

**Comment by yurisuika** [comment]
Additionally, it seems that the sharp character such as in the album F♯ A♯ ∞ is displayed as an emoji, although this maybe be a global Android bug it seems.

**Comment by karimknaebel** [comment]
This is an Android encoding "bug". Sorry, but won't fix.

**Comment by arkon** [comment]
See #128.
