### ISSUE TITLE
Twitter link doesn't work

### ISSUE THREAD

**Issue by alex-thibodeau** [karimknaebel/phonograph-issue-tracker#33]
This is small and probably doesn't matter, but I was looking at the app's about section and just tapping on stuff, and when I tapped on the "follow on Twitter" button, it didn't work. It took me to https://ic_twitter_white_24dp.com/karim23697, which isn't a real website. Someone could easily find your twitter from there, but still.

**Comment by karimknaebel** [comment]
Thx for reporting, will fix that :)

**Comment by karimknaebel** [comment]
Fixed internally.
