### ISSUE TITLE
Double statusbar

### ISSUE THREAD

**Issue by grayk79** [karimknaebel/phonograph-issue-tracker#35]
After changing app's theme to dark a little status bar like peace of free space added to top.

Sorry, no table because I don't know how to write it from mobile, but there's general info and screenshot.

App version - 0.11.0 RC
Android version - 6.0.1
Android SDK version - 23
Device model - Samsung Galaxy S4 (gt-i9500)
ROM - cm13

Screenshot - http://i.imgur.com/kzG65xo.png

**Comment by grayk79** [comment]
OK, now I see that phonograph doesn't want to integrate with my status bar. Got a little video of it, sorry for potato quality.
https://youtu.be/Zt3-fbLtnbE

**Comment by grayk79** [comment]
It was Lollistat causing this multi status bar. Turning off phonograph in it's settings solved the issue. But I'm still curios why that was only happening with dark theme?

**Comment by karimknaebel** [comment]
I don't know why its happening with the dark theme only. Must be Lollistat related too. I'm currently using a kinda hacky way to realize the transparent statusbar.
