### ISSUE TITLE
Playback control notification does not appear

### ISSUE THREAD

**Issue by NaoPross** [karimknaebel/phonograph-issue-tracker#38]
As the title says, since the last update the playback control in the notification bar does not appear anymore.

```
(for some reason github's markdown doesn't let me create a normal table)
+----------------------------------------------+
| Device             | OnePlus One Becon A0001 |
| Android Version    | 5.1.1                   |
| SDK API Version    | 22                      |
| ROM                | BlissPop 4.0            |
| Phonograph Version | 0.11.0.RC               |
+----------------------------------------------+
```

Here are few screenshots:
![screenshot_2016-05-08-17-06-31](https://cloud.githubusercontent.com/assets/13507582/15098534/41d4166e-1540-11e6-930b-f44862f9b918.png)
![screenshot_2016-05-08-17-11-26](https://cloud.githubusercontent.com/assets/13507582/15098535/41d54566-1540-11e6-90d3-81ac6de48c25.png)

**Comment by karimknaebel** [comment]
Maybe you've blocked the notification. Have a look in your settings app.

**Comment by NaoPross** [comment]
I've already checked and notifications are enabled. Also, I've asked to a friend if he has the same issue, but on his phone it's working fine (Nexus 5 with Marshmallow 6.0).

**Comment by NaoPross** [comment]
Sorry i had accidentally clicked the wrong button

**Comment by NaoPross** [comment]
Okay, I have found what caused the notification to disappear. I'm not sure if it's just my rom but on the notification settings (the one that appears when you long press) there's a button that adds a filter, which causes it to not show up. Anyway, sorry for the inconvenience. I should have checked better before posting an issue.
![screenshot_2016-05-09-18-34-06 01](https://cloud.githubusercontent.com/assets/13507582/15120351/9e075f56-1615-11e6-8818-8ace785aa2b1.png)
