### ISSUE TITLE
No order

### ISSUE THREAD

**Issue by asherheilbron** [karimknaebel/phonograph-issue-tracker#4]
There is no order in the beginning of my library (the rest is fine) but it's kind of random (5,b,e,r,1,a,b,c)
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.0 BETA 1</td></tr>
<tr><td>App version code</td><td>111</td></tr>
<tr><td>Android build version</td><td>e36dd78050</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29V</td></tr>
<tr><td>Device brand</td><td>oneplus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>A0001</td></tr>
<tr><td>Device model</td><td>A0001</td></tr>
<tr><td>Device product name</td><td>bacon</td></tr>
<tr><td>Device hardware name</td><td>bacon</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by karimknaebel** [comment]
I use androids media store provided sorting. I won't fix that. If this really annoys you, you can search for this problem on the internet. This should also happen with most other players you have installed. (Excluding Play Music, PowerAMP and GoneMad, as they use their own media store.)

**Comment by asherheilbron** [comment]
Well, it doesn't happen in other media player, and it didn't happen in the
last versions so I don't know what you're meaning by "androids media store
provided sorting"

Like you can see in this screenshot for example, is that the album "1" (who
is supposed to be the first) is after the number 5, the letter "b", "e",
"r" and "u". Tried to figure out the logics behind this order but found
none.
On Apr 17, 2016 13:34, "Karim Abou Zeid" notifications@github.com wrote:

I use androids media store provided sorting. I won't fix that. If this
really annoys you, you can search for this problem on the internet. This
should also happen with most other players you have installed. (Excluding
Play Music, PowerAMP and GoneMad, as they use their own media store.)

**Comment by karimknaebel** [comment]
I can't view the screenshot, as you are answering by mail. You must upload the screenshot from the issues website (https://github.com/kabouzeid/phonograph-issue-tracker/issues/4).
With which media players does it work?
