### ISSUE TITLE
Songs from different disc isn't sorted correctly.

### ISSUE THREAD

**Issue by anursetiawan** [karimknaebel/phonograph-issue-tracker#41]
Device: Xiaomi Redmi 3 and Samsung Galaxy Tab 2
Android version: both 5.1.1
App version: both 0.11.0 RC

Say an album has 2 disc with each 5 songs, phonograph sorts all 10 songs by the track number only, disregarding disc number, so it becomes 11 22 33 44 55. In Poweramp, WMP, and Groove, the album is sorted correctly as 12345 12345, which is the correct behavior. All song files are properly tagged.

**Comment by karimknaebel** [comment]
These apps use a custom media scanner.
