### ISSUE TITLE
Deleting a song makes player stop playing

### ISSUE THREAD

**Issue by nspacedust** [karimknaebel/phonograph-issue-tracker#43]
I don't it's a bug or you intended to make it behave thos way. When I delete any song from now playing, player stops playing, instead it should play the next song in the queue.

**Comment by nspacedust** [comment]
I don't know it's a bug or you intended to make it behave this way. When I delete any song from now playing, player stops playing, instead it should play the next song in the queue.

**Comment by karimknaebel** [comment]
It's intended.

**Comment by nspacedust** [comment]
But why? I have a huge collection so I delete songs several time and it sucks when I delete the song and it stops playing and then I have to press play again.
