### ISSUE TITLE
Song deleting bug

### ISSUE THREAD

**Issue by nspacedust** [karimknaebel/phonograph-issue-tracker#44]
Whenever I delete song it shows delete and even it is not visible in library but after app restart that song appear again, so I tried deleting a song and then I checked with my file explorer the song was not delete instead the album art of that song was deleted. I'm using marshmallow and have granted all the permissions.
## Device info:

<table>
<tr><td>App version</td><td>0.13.0 BETA 2</td></tr>
<tr><td>App version code</td><td>112</td></tr>
<tr><td>Android build version</td><td>K50a40_S424_160328_ROW</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>K50a40_S424_160328_ROW</td></tr>
<tr><td>Device brand</td><td>Lenovo</td></tr>
<tr><td>Device manufacturer</td><td>LENOVO</td></tr>
<tr><td>Device name</td><td>K50a40</td></tr>
<tr><td>Device model</td><td>Lenovo K50a40</td></tr>
<tr><td>Device product name</td><td>aio_otfp</td></tr>
<tr><td>Device hardware name</td><td>mt6752</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by karimknaebel** [comment]
Does that happen with other music players too?

**Comment by nspacedust** [comment]
Yes nearly with all of them. Only works with Musixmatch Player. I think something is wrong with marshmallow. Ya and If delete any song which is stored in internal memory it works but only songs present in wxternal sd card doesn't get deleted.

**Comment by karimknaebel** [comment]
As you've said, I don't think it is a Phonograph specific/related bug. Probably won't try to fix that, sorry.
