### ISSUE TITLE
Lock Screen Control Not Showing

### ISSUE THREAD

**Issue by danielstoiloff** [karimknaebel/phonograph-issue-tracker#46]
Lock screen controls do not show, just background image.
Device is set to show all notification content with no special notification setting for Phonograph.

| Device Info: | # |
| --- | --- |
| App Version | 0.11.0 RC |
| Android version | 6.0.1 |
| Device name: | Sony Xperia Z3 Compact |
| Model Number: | D5803 |

**Comment by karimknaebel** [comment]
Double check the notification setting for Phonograph in some ROMs (cm for example) there is another place in the settings to block notifications. Also make sure you've enabled notification content to be visible on secure lockscreen.

**Comment by karimknaebel** [comment]
Closed because its not an issue caused by Phonograph.
