### ISSUE TITLE
Custom notification font color

### ISSUE THREAD

**Issue by Wulgaren** [karimknaebel/phonograph-issue-tracker#48]
My notification has black font and it's barely visible. Here's what I'm talking about: http://imgur.com/fbzuMyj
My phone is Honor 7, Android 6.0 EMUI 4.0

**Comment by karimknaebel** [comment]
Maybe I'll add an option to set a notification text color in a future update.

**Comment by Wulgaren** [comment]
Thanks, by the way when can we expect the update to come out?

**Comment by karimknaebel** [comment]
Not too soon, there are currently higher priority features and fixes. Also I don't have much time for this project at the moment.

**Comment by arkon** [comment]
Sort of a duplicate of #17.
