### ISSUE TITLE
Music sometimes stops playing when clicking on notification.

### ISSUE THREAD

**Issue by Wulgaren** [karimknaebel/phonograph-issue-tracker#49]
My phone is Honor 7, Android 6.0, EMUI 4.0

**Comment by karimknaebel** [comment]
What do you mean exactly?

**Comment by Wulgaren** [comment]
When I listen to music, and I click on notification (cover art or track
name) for example to change to different track, music sometimes pauses and
I have to click play button to resume it.

EMUI changes the notification to smaller one constantly, so I can't make it
bigger forever, but it also happens on LG, which doesn't have this "smaller
notification thing".

**Comment by arkon** [comment]
@Wulgaren Are you still experiencing this?

**Comment by Wulgaren** [comment]
I don't use Phonograph anymore

**Comment by arkon** [comment]
@Wulgaren Fair enough. I'll close this then, since I can't reproduce it.
