### ISSUE TITLE
Empty notification when clearing the playing queue

### ISSUE THREAD

**Issue by Benny004** [karimknaebel/phonograph-issue-tracker#5]
When i delete the playing queue in the notification bar show up an empty playing panel.
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.0 BETA 1</td></tr>
<tr><td>App version code</td><td>111</td></tr>
<tr><td>Android build version</td><td>G920FXXU3DPBG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29K.G920FXXU3DPBG</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>zeroflte</td></tr>
<tr><td>Device model</td><td>SM-G920F</td></tr>
<tr><td>Device product name</td><td>zerofltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7420</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by karimknaebel** [comment]
Will fix that.
