### ISSUE TITLE
Songs disappeared from and can't be re-added to library after software update 

### ISSUE THREAD

**Issue by CherryLax** [karimknaebel/phonograph-issue-tracker#51]
The songs in my library have all disappeared, all the ones on my SD card that is. The three songs in my phone storage are still visible. 

I haven't gotten them back and I've tried clearing the app cache/data, re-adding the songs, and reinstalling the app. When I go to re-add the songs nothing happens. When I scan the folder they're in it seems to scan each song correctly but none of them show up in the library. 

I'm using a Samsung Galaxy s5 with software version 5.1.1

There was some kind of update for Android just recently so maybe that screwed with it.

**Comment by CherryLax** [comment]
0.11.0 RC is the app version I'm using btw

**Comment by karimknaebel** [comment]
Android related bug. Try to clear the app data of the Media Store.
