### ISSUE TITLE
[feature request] Add last.fm/libre.fm song scrobbling

### ISSUE THREAD

**Issue by llucax** [karimknaebel/phonograph-issue-tracker#52]
Hi, it would be nice to add support to send played songs to last.fm / libre.fm. Alternatively I don't know if it's possible to sort of register the application as an Android media player so the [Simple Last.fm Scrobbler](https://play.google.com/store/apps/details?id=com.adam.aslfms) app can take care of it.

**Comment by karimknaebel** [comment]
Already implemented. Simply install the official last.fm app, it'll work.

**Comment by llucax** [comment]
Oh, and Libre.fm won't ever be supported?
