### ISSUE TITLE
Home screen widget stops showing songs

### ISSUE THREAD

**Issue by LordSushiPhoenix** [karimknaebel/phonograph-issue-tracker#57]
![phonograph bug](https://cloud.githubusercontent.com/assets/19640845/15638170/fdf3a796-25ea-11e6-8c46-db09a7ef5904.png)

HTC One M9
Android 6.0, HTC Sense 7.0
Phonograph 0.11.0 RC

I've used phonograph for about a day (love it btw), and I've noticed the home screen widget stop working multiple times. It typically starts by getting stuck on one song, meaning it will display a song even if that's not the song that's playing, and the controls still work despite the song displayed not changing. Eventually all content from the widget disappears, as seen in the attached image. Restarting my phone fixes the issue, but it has happened multiple times over the course of a day.

**Comment by arkon** [comment]
Does this still happen?

**Comment by LordSushiPhoenix** [comment]
Nope, was fixed in an update months ago.

**Comment by arkon** [comment]
Awesome!
