### ISSUE TITLE
Refresh media library manually

### ISSUE THREAD

**Issue by butaixianran** [karimknaebel/phonograph-issue-tracker#60]
As we know, Android's media library won't refresh the list when we delete some songs, I have to reboot my phone to make it right, which is insane. 

A lot of people don't know media library at all, when some deleted songs still listed in phonograph, they'll just think it's a phonograpg's bug. 

Add a button to refresh media library could be very useful.

Many players don't even use android's media library, they scan folders to look up media files, so they don't have this problem, which phonograph has.

**Comment by karimknaebel** [comment]
You can manually rescan a folder by using phonographs inbuilt folder browser.
Also this is a bug with your ROM then, because normally, when you delete a song, Android should trigger a rescan by itself.

**Comment by butaixianran** [comment]
Hi, it's not a bug with my ROM, I add/delete songs within other music player, which can download songs directly. But these music players have their own media library system, so they won't refresh Android's media library after downloading or deleting songs. 

As you can see, you already got some issues about refresh media library (and you close them all), because those users did the same thing as I did: add/delete songs with other music players, and try to listen these songs with phonograph.

Normally, I should ask those music players to refresh Android's media library, but they'll never do that since they already have their own media library system.

**Comment by karimknaebel** [comment]
Well, then it's up to them to fix that issue.
