### ISSUE TITLE
Sound bug at the end of last song

### ISSUE THREAD

**Issue by Wulgaren** [karimknaebel/phonograph-issue-tracker#62]
After the end of the last song of queue, we can hear the beginning of the last track for a second and it's kinda annoying. Could you please fix it? Honor 7, android 6.0

**Comment by karimknaebel** [comment]
App version? Also I can't reproduce this issue. Does it happen with other music players too?

**Comment by Wulgaren** [comment]
0.13.0 Beta 4, but now I can't reproduce it too. Weird
