### ISSUE TITLE
Normalization setting

### ISSUE THREAD

**Issue by Wulgaren** [karimknaebel/phonograph-issue-tracker#63]
Could you add normalise volume setting like in Spotify? This could be a very important feature in the future, cause it may stop the loudness war and make music sound better.

**Comment by Wulgaren** [comment]
Here is a video that talks about it: https://youtu.be/dj8Y8ti85Z8

**Comment by karimknaebel** [comment]
No, this feature won't come, sorry. I try to stick to the basics.
