### ISSUE TITLE
Icons reanimating in flat now playing view when sliding down or up.

### ISSUE THREAD

**Issue by alex-thibodeau** [karimknaebel/phonograph-issue-tracker#65]
In the flat now playing view, if you start to slide the now playing panel down, at all, then return it to the normal state, the media control icons will redrawn. In addition, if you swipe up on the panel when it's already up, the icons also redraw.
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.0</td></tr>
<tr><td>App version code</td><td>115</td></tr>
<tr><td>Android build version</td><td>2741993</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MTC19T</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Huawei</td></tr>
<tr><td>Device name</td><td>angler</td></tr>
<tr><td>Device model</td><td>Nexus 6P</td></tr>
<tr><td>Device product name</td><td>angler</td></tr>
<tr><td>Device hardware name</td><td>angler</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by alex-thibodeau** [comment]
Demo:
![](https://media.giphy.com/media/2qpYNVWL4yKsM/giphy.gif)

**Comment by karimknaebel** [comment]
Will fix that soon

**Comment by arkon** [comment]
Duplicate of https://github.com/kabouzeid/Phonograph/issues/101
