### ISSUE TITLE
Add support to Simple Last.fm Scrobbler

### ISSUE THREAD

**Issue by darkon5** [karimknaebel/phonograph-issue-tracker#67]
Thre is an app called Simple Last.fm Scrobbler that shares the music you played with the Last.fm service. It would be very useful to the users of LastFM. Otjer apps such Shuttle already have it. PD: Thanks for developing this amazing app!
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.0</td></tr>
<tr><td>App version code</td><td>115</td></tr>
<tr><td>Android build version</td><td>22d37c7c83</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MHC19Q release-keys</td></tr>
<tr><td>Device brand</td><td>oneplus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>A0001</td></tr>
<tr><td>Device model</td><td>A0001</td></tr>
<tr><td>Device product name</td><td>bacon</td></tr>
<tr><td>Device hardware name</td><td>bacon</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by karimknaebel** [comment]
Simply install the official last.fm app. It'll work out of the box. I'm using it too.
