### ISSUE TITLE
Option to keep display awake while playing.

### ISSUE THREAD

**Issue by Igorskie** [karimknaebel/phonograph-issue-tracker#68]
Yo, I just wanna request if you can add an option which is; when you play music the screen will not turn off. Thanks
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.0</td></tr>
<tr><td>App version code</td><td>115</td></tr>
<tr><td>Android build version</td><td>1445332477</td></tr>
<tr><td>Android release version</td><td>5.1</td></tr>
<tr><td>Android SDK version</td><td>22</td></tr>
<tr><td>Android build ID</td><td>ALPS.L1.MP6.V2.15.2_P25</td></tr>
<tr><td>Device brand</td><td>MyPhone</td></tr>
<tr><td>Device manufacturer</td><td>MyPhone</td></tr>
<tr><td>Device name</td><td>MyPhone_MY33</td></tr>
<tr><td>Device model</td><td>MyPhone MY33</td></tr>
<tr><td>Device product name</td><td>MyPhone MY33</td></tr>
<tr><td>Device hardware name</td><td>mt6592</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by karimknaebel** [comment]
I don't exactly see the sense. What is the benefit?

**Comment by arkon** [comment]
I don't think we'll be implementing this.
