### ISSUE TITLE
Small glitch at Now Playing screen

### ISSUE THREAD

**Issue by amuhaimin02** [karimknaebel/phonograph-issue-tracker#69]
On 800x480 phone without software navigation bar, the playing queue list are incorrectly measured, leaving part of "Up Next" text visible at bottom of the screen. (When the list is closed). You'll want to fix that.

**Comment by amuhaimin02** [comment]
PS: I'm using Phonograph 0.13.0 on Android 4.4.2. But I think all 800x480 phones are affected too, (tried with 5.1.1 Samsung Galaxy Trend)

**Comment by karimknaebel** [comment]
Intended. Otherwise the user won't know there is a swipeable playing queue.
