### ISSUE TITLE
Scroll long track titles

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#70]
I read through the open and closed issues and saw 2 similar cases, which may have been unclearly described.

If you take a look at the three screenshots, you can see that they show the currently plaing song.
Unfortunately the app does not support to show the full name like f.e. play music does. Play music simply cuts off a too long name, but slides the cut off part in (whether it is in app or in notification).

It would be a nice feature, to make the whole filename visible, which is currently playing (not for the whole playlist itself, but only for currently playing title)

Why? Bevause often one would like to know the name of that song, but you simply cant or have to either unlock the phone, or open the app, go to titles and scroll down til you have found the one song.
You replied one user that the API doesnt allow this, which may be true - since i do not know. All i know is, that play musicand other (material design) players can.

This may seem like a small deal, but its a crucial user-comfort killing point.
![screenshot_20160606-194855](https://cloud.githubusercontent.com/assets/19783228/15832267/b8f62096-2c21-11e6-9ee0-dd17a2cd9406.png)
![screenshot_20160606-194851](https://cloud.githubusercontent.com/assets/19783228/15832269/c0499aee-2c21-11e6-8c36-2a94ece1789e.png)
![screenshot_20160606-194844](https://cloud.githubusercontent.com/assets/19783228/15832273/c4c818c0-2c21-11e6-8876-2ce35f3adb3d.png)

**Comment by arkon** [comment]
Tracking this in the main repo: https://github.com/kabouzeid/Phonograph/issues/200
