### ISSUE TITLE
Swipe to remove song from playlist

### ISSUE THREAD

**Issue by 5587026** [karimknaebel/phonograph-issue-tracker#71]
Hi,

Would be nice if we could swipe to remove a song from the playlist, also with an 'undo' popup. I remember, I think, that this was how Google Play Music works, and it was very handy. 

Thanks.

**Comment by karimknaebel** [comment]
I agree

**Comment by arkon** [comment]
Tracking in https://github.com/kabouzeid/Phonograph/issues/77
