### ISSUE TITLE
Exclude folder(s) option

### ISSUE THREAD

**Issue by rednaxela-work** [karimknaebel/phonograph-issue-tracker#72]
A feature I've seen on another player (IIRC Blackplayer) is to exclude certain folders (for instance containing ringtones) from the music library. 

I'd like to see this on beautiful Phonograph, too!

**Comment by au5ton** [comment]
@rednaxela-work If you're concerned about preventing ringtones (or other media files) from entering your library, as I just had this problem, putting your ringtones (or other media files) within the `Android` folder will keep them from being shown under Library view AND will automatically populate them in your system settings. Screenshots from a Nexus 6P on Android 6.0.1. 

This is just a quickfix for @rednaxela-work and anyone else with the same issue, but excluding folders would be a cool feature so people don't have to add a `.nomedia` file to every directory they don't want shown in Phonograph, as that also prevents every application from finding media, even the Android system from finding ringtones.

Showing the files in ES File Explorer:

![screenshot_20160615-182541](https://cloud.githubusercontent.com/assets/4109551/16101133/f715693c-3328-11e6-8330-99ed74b08235.png)

Searching for the media from the Library view:

![screenshot_20160615-182606](https://cloud.githubusercontent.com/assets/4109551/16101139/0bb189de-3329-11e6-8e9d-98135a3f6cbc.png)

Proving the media is there, but not playable, with the Folder view: 

![screenshot_20160615-182628](https://cloud.githubusercontent.com/assets/4109551/16101142/1937c2c6-3329-11e6-8b20-c3417943bdc3.png)

System settings to change your ringtones: 

![screenshot_20160615-182821](https://cloud.githubusercontent.com/assets/4109551/16101148/1f2e97d6-3329-11e6-8cc0-b6e583c211d6.png)

**Comment by sebastinto** [comment]
Ringtones don't show up in Phonograph for me. However, files in `/system/media/audio/ui/` do, even with a .nomedia file added within the folder. Tried clearing app data, cache, uninstalling & re-installing to no avail. It's frustrating to hear some random UI audio when shuffling all songs.

**Comment by au5ton** [comment]
@tamalbuk Same here, my old comment doesn't work for me anymore

**Comment by sebastinto** [comment]
There's kind of no logic to media scanning and UI sounds on Android. Why files in `/system/media/audio/ui/` show up but not those in `/system/media/audio/ringtones/`? This happens in other media players (like Play Music) as well. This is why we need the ability to exclude folder or blacklist tracks / files.

**Comment by bonjour81** [comment]
That would be a great feature !!
I also dont want podcasts, ringtone, notifications or whatever non-music sounds in my music player :-)

despite this, the player is great !

**Comment by arkon** [comment]
Added in https://github.com/kabouzeid/Phonograph/pull/279
