### ISSUE TITLE
Tag editor lyrics support

### ISSUE THREAD

**Issue by Flare13** [karimknaebel/phonograph-issue-tracker#73]
Please add an option to add lyrics to any m4a file
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.0</td></tr>
<tr><td>App version code</td><td>115</td></tr>
<tr><td>Android build version</td><td>31</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MPB24.65-34</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>titan_umtsds</td></tr>
<tr><td>Device model</td><td>XT1068</td></tr>
<tr><td>Device product name</td><td>titan_retde</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
Added by https://github.com/kabouzeid/Phonograph/pull/99
