### ISSUE TITLE
Shuffle albums

### ISSUE THREAD

**Issue by paulheising** [karimknaebel/phonograph-issue-tracker#75]
On the TITLE-Tab, where all songs from the library are displayed, there is this nice "Random Playback" button, an easy way to start random playback all around the user's music collection.

I would love the same feature for the ALBUMS-Tab. Which just starts playing any random album from the library.

**Comment by arkon** [comment]
As suggested in #132, it should just shuffle albums as their wholes.

**Comment by arkon** [comment]
Duplicate of https://github.com/kabouzeid/Phonograph/issues/439
