### ISSUE TITLE
Multi-Disc Albums

### ISSUE THREAD

**Issue by paulheising** [karimknaebel/phonograph-issue-tracker#76]
As we all know, there are some multi-disc albums existing.

In my current example, this is "Geräusch" from "Die Ärzte"

How I organized them:
- Folder structure:
  - "Die Ärzte\Geräusch\CD 1" and "Die Ärzte\Geräusch\CD 2"
- Both directories "CD 1" and "CD 2" contain the 13 tracks from their discs, tagged like this:
  - Track number tag: both discs running from 1 to 13
  - Album Tag: "Geräusch" for all tracks. Because this is what I want to see in the player
  - Interpret Tag: "Die Ärzte" for all tracks
  - Discnumber Tag: "1" for all tracks in CD 1, and "2" for all tracks on CD 2

Now, when I move to the "Albums" Tab in Phonograph, or select "Die Ärzte" from the "Interpret" Tab, Disc 1 and 2 appear on the same level as all other albums. This is okay, but imho it whould be much better if Phonograph could do it like this:
- Show only one album "Geräusch" (because Interpret and Album Tag is equal for both)
- When selecting the album, view a headline for both discs to split them visually
- Offer buttons to start playing Disc 1 or Disc 2 directly (of course you could also select the first track of one disc, but I would prefer an explicit "play album" button, like I also stated here: https://github.com/kabouzeid/phonograph-issue-tracker/issues/15)

**Comment by karimknaebel** [comment]
This depends on how your version of Android indexes your library. Phonograph does not sort your music library on it's own, sorry.
