### ISSUE TITLE
Hide icons in playback view

### ISSUE THREAD

**Issue by paulheising** [karimknaebel/phonograph-issue-tracker#77]
In the playback view, there is the X Icon on the upper left corner, and the "heart" and "three dots" icons on the upper right corner. They are placed on the album cover.

I know, i am picky, but I would like to see the album cover icon-free, and I don't really need these icons. Because:
- Instead of X, I normally use the back-button of my phone
- Instead of the heart, I can also do the instagram-like double tap to add a song to the favourites (nice feature btw)
- Instead of the "three dots", I _would like_ to use the settings button of my phone instead (which actually doesn't work currently, but this is what I'd expect)

So, for users who have settings and back-buttons on there phones, there is no need for theese icons. It would be nice if there was a way to hide them. For example by performing a single tap on the cover to hide, and another single tap on the cover to show them again.

Or add an option to the settings to permanently hide/show the icons.

Or place them somewhere else, so they do not overlap the cover, to make picky users like me happy :D

**Comment by karimknaebel** [comment]
I understand what you mean, but I'm not sure yet if I'll implement it. I don't really want to add too many options.

**Comment by paulheising** [comment]
Then, maybe it would be best to hide the icons on single tap on the album cover, and show them again on another tap. And remember, if the icons were shown or hidden, when closing the playback view, so the icons will be in the same state if you later enter the view again.

If you did it this way, this is not an extra "option" but just a conventional way to hide the icons. It's the same thing as in the facebook app, for example, where you can also hide the ui controls by single tapping on a picture you view.

**Comment by arkon** [comment]
Already implemented.
