### ISSUE TITLE
"Play album" button and adding to queue/playlist

### ISSUE THREAD

**Issue by paulheising** [karimknaebel/phonograph-issue-tracker#78]
I also stated this somewhere else in the comments, but I wanted to make a specific issue entry for that.

I saw it in VLC for android shortly: the "Play" button, on the album view, which starts playing the selected album. This would be nice to have it in Phonograph. Of course, you could also play the album by tapping on the first song, but if you want to listen to an album, I think it's way more intuitive to have a playback button for the album. It would also be nice, if this play-button turned off shuffle, if it's turned on, because I think normally you want to listen to an album with the original track order. 

And additionally, it would also be nice to be able to add an album to the play queue directly from the album view itself. Currently this is only possible, if you long-tap the album on the album overview, but when you actually tapped on the album to view the songs, you can't add it to the queue any more.

**Comment by arkon** [comment]
Not sure about the play button, but adding an album to the queue/a playlist should be in the overflow menu.
