### ISSUE TITLE
image updates. 

### ISSUE THREAD

**Issue by scot23** [karimknaebel/phonograph-issue-tracker#8]
can you explain how to update the images (or replace what is automatically chosen) ? 
for artist -> dropdown -> update artist image
i just get   "updating .... unknown ,....  error "

for album  -> tag editor -> long-click -> update image -> web search
it opens the browser,  but then nothing happens.

**Comment by karimknaebel** [comment]
This is not an issue, but a question. Ask questions in the community https://plus.google.com/u/0/communities/106227738496107108513
