### ISSUE TITLE
File browser does not show .ogg files

### ISSUE THREAD

**Issue by bk138** [karimknaebel/phonograph-issue-tracker#81]
Hi Karim,
The file browser does not show .ogg files, they _do_ show up in the library though. Issue also reported at https://plus.google.com/+AdrianVovkDev/posts/Lt9u4bGWUDo. Should be an easy fix.

**Comment by arkon** [comment]
Fixed in https://github.com/kabouzeid/Phonograph/commit/eeb67e2defa99fcb56529555aa5b1bef8f4139d3
