### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by YellowZaki** [karimknaebel/phonograph-issue-tracker#83]
When I search a song, when it finishes playing I would like to listen the next songs.
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>2741993</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MTC19T</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>bullhead</td></tr>
<tr><td>Device model</td><td>Nexus 5X</td></tr>
<tr><td>Device product name</td><td>bullhead</td></tr>
<tr><td>Device hardware name</td><td>bullhead</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by arkon** [comment]
It should be up to the user to manage their play queue.
