### ISSUE TITLE
Album art is replaced by gallery photos

### ISSUE THREAD

**Issue by klavbruno** [karimknaebel/phonograph-issue-tracker#84]
The album art shown in some of the songs is a random photo from the gallery, instead of the cover.

**Comment by Miridyan** [comment]
I am experiencing the same issue. Here is a screenshot of it.

![screenshot_20160616-181326](https://cloud.githubusercontent.com/assets/13137402/16135169/b7225a16-33ef-11e6-8efb-214a3fc4af00.png)

**Comment by dfunstufff** [comment]
Yes, but in my case only in the small thumbnails. When I open he playing panel, it shows the real album art.

**Comment by darthbatman12** [comment]
The same happens for me, the album art in thumbnails is random gallery photos, but in the album's panel it shows up correctly.

**Comment by David-Byrne** [comment]
I had this issue as well on my Oneplus X, running android 6.0.1. It only affected 2 songs, "Beautiful Day" by U2 and "99 Red Balloons" by Nena. No other music apps I tried used the incorrect images.

For "99 Red Balloons", only the thumbnail in the list of songs was wrong, the image when it was being played was correct. For "Beautiful Day", the image was wrong both in the thumbnail and while playing.  

Removing and re-adding the .mp3 files to the SD card didn't fix the problem. A fix I found was to delete the photo that was being used as the cover art. Putting the photo back afterwards didn't cause the problem to re-appear.

If you need any more information I'll be happy to help.

**Comment by arkon** [comment]
Tracking in https://github.com/kabouzeid/Phonograph/issues/198
