### ISSUE TITLE
Higher quality art support (?)

### ISSUE THREAD

**Issue by GuardOfInsanity** [karimknaebel/phonograph-issue-tracker#87]
The app enters a terrible deadlock when playing tracks from albums which have really high quality arts (Savant - 9000x9000). Would it be possible to fix such problem o.O?
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>G900FXXU1CPD3</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.G900FXXU1CPD3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>klte</td></tr>
<tr><td>Device model</td><td>SM-G900F</td></tr>
<tr><td>Device product name</td><td>kltexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
Related to #112
