### ISSUE TITLE
Albums' "Color"

### ISSUE THREAD

**Issue by GuardOfInsanity** [karimknaebel/phonograph-issue-tracker#88]
Phonograph has the function to colour the frame of albums based on their natural patterns, but sometimes the outcome is incorrect. It would be great to be able to manually set the frame's colour!
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>G900FXXU1CPD3</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.G900FXXU1CPD3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>klte</td></tr>
<tr><td>Device model</td><td>SM-G900F</td></tr>
<tr><td>Device product name</td><td>kltexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment]
This relies on Google's palette library so it's a bit outside of our control. I don't think we'll be adding this feature though, as it adds quite a bit complexity (i.e. storing the data).
