### ISSUE TITLE
Sugerencia 

### ISSUE THREAD

**Issue by bdani0** [karimknaebel/phonograph-issue-tracker#92]
Hola, me llamó Daniel y mi sugerencia es que mejoren un poco mas la fluidez al subir y bajar entre los álbumes
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>c6f5d56100</td></tr>
<tr><td>Android release version</td><td>4.4.4</td></tr>
<tr><td>Android SDK version</td><td>19</td></tr>
<tr><td>Android build ID</td><td>KTU84Q</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>titan_umtsds</td></tr>
<tr><td>Device model</td><td>Moto G 2014</td></tr>
<tr><td>Device product name</td><td>cm_titan</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>null</td></tr>
<tr><td>ABIs (64bit)</td><td>null</td></tr>
</table>

**Comment by arkon** [comment]
What do you mean?

**Comment by bdani0** [comment]
I'm sorry, I just needed to update my operative system, the problem is solved, I currently have Android 7.1.2
Thank you so much

**Comment by bdani0** [comment]
I'm sorry, I just needed to update my operative system, the problem is solved, I currently have Android 7.1.2
Thank you so much
