### ISSUE TITLE
Phonograph doesn't provide music info for other apps

### ISSUE THREAD

**Issue by alffn** [karimknaebel/phonograph-issue-tracker#94]
Every time I try to get music information from other apps from phonograph, the apps cannot get any information. Therefore, the app just show the info as blank (KLWP).

In musixmatch, there are floating lyrics. And the lyrics often scrolls to follow the progression of the music. But, in phonograph, the lyrics just stayed.

That's all I know about this
I hope you find and solve the issue soon!

**Comment by arkon** [comment]
FloatingLyrics seems to work fine for me. I assume KLWP listens for [the same broadcast intents](https://developer.musixmatch.com/documentation/floating-lyrics), so hopefully that works fine too.
