### ISSUE TITLE
[request] Support LG dual window

### ISSUE THREAD

**Issue by SZE2** [karimknaebel/phonograph-issue-tracker#99]
Google+ link: https://plus.google.com/116769038214630577552/posts/XBqtzbU6mVG

Content:
Could you please add support for LG's dual window mode?

It should be a super simple edit to the Manifest.xml see the official LG site:

Www.developer.lge.com/resource/mobile/RetrieveOverview.dev?categoryTypeCode=ANRS#RS00000848

I'd be willing to test builds for you if you do not have a LG phone.

This would enable users on LG to have your app on-screen together with Google maps while driving, something I've wanted for a while.

Thank you!
﻿

**Comment by arkon** [comment]
Working link: http://mobile.developer.lge.com/develop/dev-guides/lg-dual-window-guide/development/enabling-dual-window/
